/* Generated by Yosys 0.5+ (git sha1 ba4cce9, gcc 4.8.4-2ubuntu1~14.04 -O2 -fstack-protector -fPIC -Os) */

module \$paramod\SERIAL_TO_PARALLEL\SIZE=32 (serial_in, enable_stp, SD_CLK, RESET_L, reception_complete, parallel_out);
  wire [8:0] _000_;
  wire [31:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire [31:0] _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire [3:0] _368_;
  wire [1:0] _369_;
  wire _370_;
  wire [8:0] _371_;
  wire _372_;
  wire _373_;
  wire [31:0] _374_;
  wire [8:0] _375_;
  wire [31:0] _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  input RESET_L;
  input SD_CLK;
  wire [8:0] contador;
  input enable_stp;
  output [31:0] parallel_out;
  output reception_complete;
  input serial_in;
  NOT _381_ (
    .A(_003_),
    .Y(_004_)
  );
  NOT _382_ (
    .A(_130_),
    .Y(_024_)
  );
  NAND _383_ (
    .A(_024_),
    .B(_111_),
    .Y(_025_)
  );
  NOR _384_ (
    .A(_055_),
    .B(_314_),
    .Y(_026_)
  );
  NAND _385_ (
    .A(_026_),
    .B(_044_),
    .Y(_027_)
  );
  NOR _386_ (
    .A(_034_),
    .B(_030_),
    .Y(_028_)
  );
  NOT _387_ (
    .A(_139_),
    .Y(_029_)
  );
  NOT _388_ (
    .A(_226_),
    .Y(_031_)
  );
  NAND _389_ (
    .A(_031_),
    .B(_029_),
    .Y(_033_)
  );
  NOT _390_ (
    .A(_291_),
    .Y(_035_)
  );
  NOT _391_ (
    .A(_307_),
    .Y(_037_)
  );
  NAND _392_ (
    .A(_037_),
    .B(_035_),
    .Y(_039_)
  );
  NOR _393_ (
    .A(_039_),
    .B(_033_),
    .Y(_041_)
  );
  NAND _394_ (
    .A(_041_),
    .B(_028_),
    .Y(_043_)
  );
  NOR _395_ (
    .A(_043_),
    .B(_027_),
    .Y(_045_)
  );
  NAND _396_ (
    .A(_045_),
    .B(_130_),
    .Y(_047_)
  );
  NAND _397_ (
    .A(_047_),
    .B(_025_),
    .Y(_140_)
  );
  NOT _398_ (
    .A(_158_),
    .Y(_050_)
  );
  NOR _399_ (
    .A(_045_),
    .B(_050_),
    .Y(_052_)
  );
  NOT _400_ (
    .A(_149_),
    .Y(_054_)
  );
  NOT _401_ (
    .A(_027_),
    .Y(_057_)
  );
  NOT _402_ (
    .A(_028_),
    .Y(_059_)
  );
  NOR _403_ (
    .A(_226_),
    .B(_139_),
    .Y(_061_)
  );
  NOR _404_ (
    .A(_307_),
    .B(_291_),
    .Y(_063_)
  );
  NAND _405_ (
    .A(_063_),
    .B(_061_),
    .Y(_065_)
  );
  NOR _406_ (
    .A(_065_),
    .B(_059_),
    .Y(_067_)
  );
  NAND _407_ (
    .A(_067_),
    .B(_057_),
    .Y(_069_)
  );
  NOR _408_ (
    .A(_069_),
    .B(_054_),
    .Y(_071_)
  );
  NOR _409_ (
    .A(_071_),
    .B(_052_),
    .Y(_073_)
  );
  NOR _410_ (
    .A(_073_),
    .B(_024_),
    .Y(_311_)
  );
  NOT _411_ (
    .A(_175_),
    .Y(_076_)
  );
  NOR _412_ (
    .A(_045_),
    .B(_076_),
    .Y(_078_)
  );
  NOR _413_ (
    .A(_069_),
    .B(_050_),
    .Y(_080_)
  );
  NOR _414_ (
    .A(_080_),
    .B(_078_),
    .Y(_082_)
  );
  NOR _415_ (
    .A(_082_),
    .B(_024_),
    .Y(_312_)
  );
  NOT _416_ (
    .A(_192_),
    .Y(_085_)
  );
  NOR _417_ (
    .A(_045_),
    .B(_085_),
    .Y(_087_)
  );
  NOR _418_ (
    .A(_069_),
    .B(_076_),
    .Y(_089_)
  );
  NOR _419_ (
    .A(_089_),
    .B(_087_),
    .Y(_091_)
  );
  NOR _420_ (
    .A(_091_),
    .B(_024_),
    .Y(_313_)
  );
  NOT _421_ (
    .A(_209_),
    .Y(_094_)
  );
  NOR _422_ (
    .A(_045_),
    .B(_094_),
    .Y(_096_)
  );
  NOR _423_ (
    .A(_069_),
    .B(_085_),
    .Y(_098_)
  );
  NOR _424_ (
    .A(_098_),
    .B(_096_),
    .Y(_100_)
  );
  NOR _425_ (
    .A(_100_),
    .B(_024_),
    .Y(_315_)
  );
  NOT _426_ (
    .A(_227_),
    .Y(_103_)
  );
  NOR _427_ (
    .A(_045_),
    .B(_103_),
    .Y(_105_)
  );
  NOR _428_ (
    .A(_069_),
    .B(_094_),
    .Y(_107_)
  );
  NOR _429_ (
    .A(_107_),
    .B(_105_),
    .Y(_109_)
  );
  NOR _430_ (
    .A(_109_),
    .B(_024_),
    .Y(_316_)
  );
  NOT _431_ (
    .A(_244_),
    .Y(_113_)
  );
  NOR _432_ (
    .A(_045_),
    .B(_113_),
    .Y(_115_)
  );
  NOR _433_ (
    .A(_069_),
    .B(_103_),
    .Y(_117_)
  );
  NOR _434_ (
    .A(_117_),
    .B(_115_),
    .Y(_119_)
  );
  NOR _435_ (
    .A(_119_),
    .B(_024_),
    .Y(_317_)
  );
  NOT _436_ (
    .A(_262_),
    .Y(_122_)
  );
  NOR _437_ (
    .A(_045_),
    .B(_122_),
    .Y(_124_)
  );
  NOR _438_ (
    .A(_069_),
    .B(_113_),
    .Y(_126_)
  );
  NOR _439_ (
    .A(_126_),
    .B(_124_),
    .Y(_128_)
  );
  NOR _440_ (
    .A(_128_),
    .B(_024_),
    .Y(_318_)
  );
  NOT _441_ (
    .A(_280_),
    .Y(_131_)
  );
  NOR _442_ (
    .A(_045_),
    .B(_131_),
    .Y(_132_)
  );
  NOR _443_ (
    .A(_069_),
    .B(_122_),
    .Y(_133_)
  );
  NOR _444_ (
    .A(_133_),
    .B(_132_),
    .Y(_134_)
  );
  NOR _445_ (
    .A(_134_),
    .B(_024_),
    .Y(_319_)
  );
  NOT _446_ (
    .A(_285_),
    .Y(_135_)
  );
  NOR _447_ (
    .A(_045_),
    .B(_135_),
    .Y(_136_)
  );
  NOR _448_ (
    .A(_069_),
    .B(_131_),
    .Y(_137_)
  );
  NOR _449_ (
    .A(_137_),
    .B(_136_),
    .Y(_138_)
  );
  NOR _450_ (
    .A(_138_),
    .B(_024_),
    .Y(_320_)
  );
  NOT _451_ (
    .A(_286_),
    .Y(_141_)
  );
  NOR _452_ (
    .A(_045_),
    .B(_141_),
    .Y(_142_)
  );
  NOR _453_ (
    .A(_069_),
    .B(_135_),
    .Y(_143_)
  );
  NOR _454_ (
    .A(_143_),
    .B(_142_),
    .Y(_144_)
  );
  NOR _455_ (
    .A(_144_),
    .B(_024_),
    .Y(_321_)
  );
  NOT _456_ (
    .A(_287_),
    .Y(_145_)
  );
  NOR _457_ (
    .A(_045_),
    .B(_145_),
    .Y(_146_)
  );
  NOR _458_ (
    .A(_069_),
    .B(_141_),
    .Y(_147_)
  );
  NOR _459_ (
    .A(_147_),
    .B(_146_),
    .Y(_148_)
  );
  NOR _460_ (
    .A(_148_),
    .B(_024_),
    .Y(_322_)
  );
  NOT _461_ (
    .A(_288_),
    .Y(_150_)
  );
  NOR _462_ (
    .A(_045_),
    .B(_150_),
    .Y(_151_)
  );
  NOR _463_ (
    .A(_069_),
    .B(_145_),
    .Y(_152_)
  );
  NOR _464_ (
    .A(_152_),
    .B(_151_),
    .Y(_153_)
  );
  NOR _465_ (
    .A(_153_),
    .B(_024_),
    .Y(_323_)
  );
  NOT _466_ (
    .A(_289_),
    .Y(_154_)
  );
  NOR _467_ (
    .A(_045_),
    .B(_154_),
    .Y(_155_)
  );
  NOR _468_ (
    .A(_069_),
    .B(_150_),
    .Y(_156_)
  );
  NOR _469_ (
    .A(_156_),
    .B(_155_),
    .Y(_157_)
  );
  NOR _470_ (
    .A(_157_),
    .B(_024_),
    .Y(_324_)
  );
  NOT _471_ (
    .A(_290_),
    .Y(_159_)
  );
  NOR _472_ (
    .A(_045_),
    .B(_159_),
    .Y(_160_)
  );
  NOR _473_ (
    .A(_069_),
    .B(_154_),
    .Y(_161_)
  );
  NOR _474_ (
    .A(_161_),
    .B(_160_),
    .Y(_162_)
  );
  NOR _475_ (
    .A(_162_),
    .B(_024_),
    .Y(_005_)
  );
  NOT _476_ (
    .A(_292_),
    .Y(_163_)
  );
  NOR _477_ (
    .A(_045_),
    .B(_163_),
    .Y(_164_)
  );
  NOR _478_ (
    .A(_069_),
    .B(_159_),
    .Y(_165_)
  );
  NOR _479_ (
    .A(_165_),
    .B(_164_),
    .Y(_166_)
  );
  NOR _480_ (
    .A(_166_),
    .B(_024_),
    .Y(_006_)
  );
  NOT _481_ (
    .A(_293_),
    .Y(_167_)
  );
  NOR _482_ (
    .A(_045_),
    .B(_167_),
    .Y(_168_)
  );
  NOR _483_ (
    .A(_069_),
    .B(_163_),
    .Y(_169_)
  );
  NOR _484_ (
    .A(_169_),
    .B(_168_),
    .Y(_170_)
  );
  NOR _485_ (
    .A(_170_),
    .B(_024_),
    .Y(_007_)
  );
  NOT _486_ (
    .A(_294_),
    .Y(_171_)
  );
  NOR _487_ (
    .A(_045_),
    .B(_171_),
    .Y(_172_)
  );
  NOR _488_ (
    .A(_069_),
    .B(_167_),
    .Y(_173_)
  );
  NOR _489_ (
    .A(_173_),
    .B(_172_),
    .Y(_174_)
  );
  NOR _490_ (
    .A(_174_),
    .B(_024_),
    .Y(_008_)
  );
  NOT _491_ (
    .A(_295_),
    .Y(_176_)
  );
  NOR _492_ (
    .A(_045_),
    .B(_176_),
    .Y(_177_)
  );
  NOR _493_ (
    .A(_069_),
    .B(_171_),
    .Y(_178_)
  );
  NOR _494_ (
    .A(_178_),
    .B(_177_),
    .Y(_179_)
  );
  NOR _495_ (
    .A(_179_),
    .B(_024_),
    .Y(_009_)
  );
  NOT _496_ (
    .A(_296_),
    .Y(_180_)
  );
  NOR _497_ (
    .A(_045_),
    .B(_180_),
    .Y(_181_)
  );
  NOR _498_ (
    .A(_069_),
    .B(_176_),
    .Y(_182_)
  );
  NOR _499_ (
    .A(_182_),
    .B(_181_),
    .Y(_183_)
  );
  NOR _500_ (
    .A(_183_),
    .B(_024_),
    .Y(_010_)
  );
  NOT _501_ (
    .A(_297_),
    .Y(_184_)
  );
  NOR _502_ (
    .A(_045_),
    .B(_184_),
    .Y(_185_)
  );
  NOR _503_ (
    .A(_069_),
    .B(_180_),
    .Y(_186_)
  );
  NOR _504_ (
    .A(_186_),
    .B(_185_),
    .Y(_187_)
  );
  NOR _505_ (
    .A(_187_),
    .B(_024_),
    .Y(_011_)
  );
  NOT _506_ (
    .A(_298_),
    .Y(_188_)
  );
  NOR _507_ (
    .A(_045_),
    .B(_188_),
    .Y(_189_)
  );
  NOR _508_ (
    .A(_069_),
    .B(_184_),
    .Y(_190_)
  );
  NOR _509_ (
    .A(_190_),
    .B(_189_),
    .Y(_191_)
  );
  NOR _510_ (
    .A(_191_),
    .B(_024_),
    .Y(_012_)
  );
  NOT _511_ (
    .A(_299_),
    .Y(_193_)
  );
  NOR _512_ (
    .A(_045_),
    .B(_193_),
    .Y(_194_)
  );
  NOR _513_ (
    .A(_069_),
    .B(_188_),
    .Y(_195_)
  );
  NOR _514_ (
    .A(_195_),
    .B(_194_),
    .Y(_196_)
  );
  NOR _515_ (
    .A(_196_),
    .B(_024_),
    .Y(_013_)
  );
  NOT _516_ (
    .A(_300_),
    .Y(_197_)
  );
  NOR _517_ (
    .A(_045_),
    .B(_197_),
    .Y(_198_)
  );
  NOR _518_ (
    .A(_069_),
    .B(_193_),
    .Y(_199_)
  );
  NOR _519_ (
    .A(_199_),
    .B(_198_),
    .Y(_200_)
  );
  NOR _520_ (
    .A(_200_),
    .B(_024_),
    .Y(_014_)
  );
  NOT _521_ (
    .A(_301_),
    .Y(_201_)
  );
  NOR _522_ (
    .A(_045_),
    .B(_201_),
    .Y(_202_)
  );
  NOR _523_ (
    .A(_069_),
    .B(_197_),
    .Y(_203_)
  );
  NOR _524_ (
    .A(_203_),
    .B(_202_),
    .Y(_204_)
  );
  NOR _525_ (
    .A(_204_),
    .B(_024_),
    .Y(_015_)
  );
  NOT _526_ (
    .A(_302_),
    .Y(_205_)
  );
  NOR _527_ (
    .A(_045_),
    .B(_205_),
    .Y(_206_)
  );
  NOR _528_ (
    .A(_069_),
    .B(_201_),
    .Y(_207_)
  );
  NOR _529_ (
    .A(_207_),
    .B(_206_),
    .Y(_208_)
  );
  NOR _530_ (
    .A(_208_),
    .B(_024_),
    .Y(_016_)
  );
  NOT _531_ (
    .A(_303_),
    .Y(_210_)
  );
  NOR _532_ (
    .A(_045_),
    .B(_210_),
    .Y(_211_)
  );
  NOR _533_ (
    .A(_069_),
    .B(_205_),
    .Y(_212_)
  );
  NOR _534_ (
    .A(_212_),
    .B(_211_),
    .Y(_213_)
  );
  NOR _535_ (
    .A(_213_),
    .B(_024_),
    .Y(_017_)
  );
  NOT _536_ (
    .A(_304_),
    .Y(_214_)
  );
  NOR _537_ (
    .A(_045_),
    .B(_214_),
    .Y(_215_)
  );
  NOR _538_ (
    .A(_069_),
    .B(_210_),
    .Y(_216_)
  );
  NOR _539_ (
    .A(_216_),
    .B(_215_),
    .Y(_217_)
  );
  NOR _540_ (
    .A(_217_),
    .B(_024_),
    .Y(_018_)
  );
  NOT _541_ (
    .A(_305_),
    .Y(_218_)
  );
  NOR _542_ (
    .A(_045_),
    .B(_218_),
    .Y(_219_)
  );
  NOR _543_ (
    .A(_069_),
    .B(_214_),
    .Y(_220_)
  );
  NOR _544_ (
    .A(_220_),
    .B(_219_),
    .Y(_221_)
  );
  NOR _545_ (
    .A(_221_),
    .B(_024_),
    .Y(_019_)
  );
  NOT _546_ (
    .A(_306_),
    .Y(_222_)
  );
  NOR _547_ (
    .A(_045_),
    .B(_222_),
    .Y(_223_)
  );
  NOR _548_ (
    .A(_069_),
    .B(_218_),
    .Y(_224_)
  );
  NOR _549_ (
    .A(_224_),
    .B(_223_),
    .Y(_225_)
  );
  NOR _550_ (
    .A(_225_),
    .B(_024_),
    .Y(_020_)
  );
  NOT _551_ (
    .A(_308_),
    .Y(_228_)
  );
  NOR _552_ (
    .A(_045_),
    .B(_228_),
    .Y(_229_)
  );
  NOR _553_ (
    .A(_069_),
    .B(_222_),
    .Y(_230_)
  );
  NOR _554_ (
    .A(_230_),
    .B(_229_),
    .Y(_231_)
  );
  NOR _555_ (
    .A(_231_),
    .B(_024_),
    .Y(_021_)
  );
  NOT _556_ (
    .A(_309_),
    .Y(_232_)
  );
  NOR _557_ (
    .A(_045_),
    .B(_232_),
    .Y(_233_)
  );
  NOR _558_ (
    .A(_069_),
    .B(_228_),
    .Y(_234_)
  );
  NOR _559_ (
    .A(_234_),
    .B(_233_),
    .Y(_235_)
  );
  NOR _560_ (
    .A(_235_),
    .B(_024_),
    .Y(_022_)
  );
  NOT _561_ (
    .A(_310_),
    .Y(_236_)
  );
  NOR _562_ (
    .A(_045_),
    .B(_236_),
    .Y(_237_)
  );
  NOR _563_ (
    .A(_069_),
    .B(_232_),
    .Y(_238_)
  );
  NOR _564_ (
    .A(_238_),
    .B(_237_),
    .Y(_239_)
  );
  NOR _565_ (
    .A(_239_),
    .B(_024_),
    .Y(_023_)
  );
  NAND _566_ (
    .A(_030_),
    .B(_024_),
    .Y(_240_)
  );
  NOR _567_ (
    .A(_045_),
    .B(_030_),
    .Y(_241_)
  );
  NAND _568_ (
    .A(_241_),
    .B(_130_),
    .Y(_242_)
  );
  NAND _569_ (
    .A(_242_),
    .B(_240_),
    .Y(_032_)
  );
  NOT _570_ (
    .A(_030_),
    .Y(_243_)
  );
  NOT _571_ (
    .A(_034_),
    .Y(_245_)
  );
  NOR _572_ (
    .A(_245_),
    .B(_243_),
    .Y(_246_)
  );
  NOR _573_ (
    .A(_246_),
    .B(_028_),
    .Y(_247_)
  );
  NOR _574_ (
    .A(_247_),
    .B(_024_),
    .Y(_248_)
  );
  NOR _575_ (
    .A(_034_),
    .B(_130_),
    .Y(_249_)
  );
  NOR _576_ (
    .A(_249_),
    .B(_248_),
    .Y(_036_)
  );
  NAND _577_ (
    .A(_246_),
    .B(_130_),
    .Y(_250_)
  );
  NOR _578_ (
    .A(_250_),
    .B(_029_),
    .Y(_251_)
  );
  NAND _579_ (
    .A(_034_),
    .B(_030_),
    .Y(_252_)
  );
  NOR _580_ (
    .A(_252_),
    .B(_024_),
    .Y(_253_)
  );
  NOR _581_ (
    .A(_253_),
    .B(_139_),
    .Y(_254_)
  );
  NOR _582_ (
    .A(_254_),
    .B(_251_),
    .Y(_038_)
  );
  NOR _583_ (
    .A(_251_),
    .B(_226_),
    .Y(_255_)
  );
  NAND _584_ (
    .A(_226_),
    .B(_139_),
    .Y(_256_)
  );
  NOR _585_ (
    .A(_256_),
    .B(_250_),
    .Y(_257_)
  );
  NOR _586_ (
    .A(_257_),
    .B(_255_),
    .Y(_040_)
  );
  NOR _587_ (
    .A(_257_),
    .B(_291_),
    .Y(_258_)
  );
  NOT _588_ (
    .A(_256_),
    .Y(_259_)
  );
  NAND _589_ (
    .A(_259_),
    .B(_253_),
    .Y(_260_)
  );
  NOR _590_ (
    .A(_260_),
    .B(_035_),
    .Y(_261_)
  );
  NOR _591_ (
    .A(_261_),
    .B(_258_),
    .Y(_042_)
  );
  NOR _592_ (
    .A(_261_),
    .B(_044_),
    .Y(_263_)
  );
  NAND _593_ (
    .A(_261_),
    .B(_044_),
    .Y(_264_)
  );
  NAND _594_ (
    .A(_264_),
    .B(_047_),
    .Y(_265_)
  );
  NOR _595_ (
    .A(_265_),
    .B(_263_),
    .Y(_046_)
  );
  NAND _596_ (
    .A(_264_),
    .B(_307_),
    .Y(_266_)
  );
  NOT _597_ (
    .A(_044_),
    .Y(_267_)
  );
  NAND _598_ (
    .A(_257_),
    .B(_291_),
    .Y(_268_)
  );
  NOR _599_ (
    .A(_268_),
    .B(_267_),
    .Y(_269_)
  );
  NAND _600_ (
    .A(_269_),
    .B(_037_),
    .Y(_270_)
  );
  NAND _601_ (
    .A(_270_),
    .B(_266_),
    .Y(_048_)
  );
  NOT _602_ (
    .A(_314_),
    .Y(_271_)
  );
  NOR _603_ (
    .A(_256_),
    .B(_252_),
    .Y(_272_)
  );
  NAND _604_ (
    .A(_307_),
    .B(_291_),
    .Y(_273_)
  );
  NAND _605_ (
    .A(_044_),
    .B(_130_),
    .Y(_274_)
  );
  NOR _606_ (
    .A(_274_),
    .B(_273_),
    .Y(_275_)
  );
  NAND _607_ (
    .A(_275_),
    .B(_272_),
    .Y(_276_)
  );
  NOR _608_ (
    .A(_276_),
    .B(_271_),
    .Y(_277_)
  );
  NOT _609_ (
    .A(_276_),
    .Y(_278_)
  );
  NOR _610_ (
    .A(_278_),
    .B(_314_),
    .Y(_279_)
  );
  NOR _611_ (
    .A(_279_),
    .B(_277_),
    .Y(_049_)
  );
  NOR _612_ (
    .A(_277_),
    .B(_055_),
    .Y(_281_)
  );
  NOT _613_ (
    .A(_055_),
    .Y(_282_)
  );
  NOT _614_ (
    .A(_277_),
    .Y(_283_)
  );
  NOR _615_ (
    .A(_283_),
    .B(_282_),
    .Y(_284_)
  );
  NOR _616_ (
    .A(_284_),
    .B(_281_),
    .Y(_051_)
  );
  BUF _617_ (
    .A(_004_),
    .Y(_053_)
  );
  BUF _618_ (
    .A(_004_),
    .Y(_056_)
  );
  BUF _619_ (
    .A(_004_),
    .Y(_058_)
  );
  BUF _620_ (
    .A(_004_),
    .Y(_060_)
  );
  BUF _621_ (
    .A(_004_),
    .Y(_062_)
  );
  BUF _622_ (
    .A(_004_),
    .Y(_064_)
  );
  BUF _623_ (
    .A(_004_),
    .Y(_066_)
  );
  BUF _624_ (
    .A(_004_),
    .Y(_068_)
  );
  BUF _625_ (
    .A(_004_),
    .Y(_070_)
  );
  BUF _626_ (
    .A(_004_),
    .Y(_072_)
  );
  BUF _627_ (
    .A(_004_),
    .Y(_074_)
  );
  BUF _628_ (
    .A(_004_),
    .Y(_075_)
  );
  BUF _629_ (
    .A(_004_),
    .Y(_077_)
  );
  BUF _630_ (
    .A(_004_),
    .Y(_079_)
  );
  BUF _631_ (
    .A(_004_),
    .Y(_081_)
  );
  BUF _632_ (
    .A(_004_),
    .Y(_083_)
  );
  BUF _633_ (
    .A(_004_),
    .Y(_084_)
  );
  BUF _634_ (
    .A(_004_),
    .Y(_086_)
  );
  BUF _635_ (
    .A(_004_),
    .Y(_088_)
  );
  BUF _636_ (
    .A(_004_),
    .Y(_090_)
  );
  BUF _637_ (
    .A(_004_),
    .Y(_092_)
  );
  BUF _638_ (
    .A(_004_),
    .Y(_093_)
  );
  BUF _639_ (
    .A(_004_),
    .Y(_095_)
  );
  BUF _640_ (
    .A(_004_),
    .Y(_097_)
  );
  BUF _641_ (
    .A(_004_),
    .Y(_099_)
  );
  BUF _642_ (
    .A(_004_),
    .Y(_101_)
  );
  BUF _643_ (
    .A(_004_),
    .Y(_102_)
  );
  BUF _644_ (
    .A(_004_),
    .Y(_104_)
  );
  BUF _645_ (
    .A(_004_),
    .Y(_106_)
  );
  BUF _646_ (
    .A(_004_),
    .Y(_108_)
  );
  BUF _647_ (
    .A(_004_),
    .Y(_110_)
  );
  BUF _648_ (
    .A(_004_),
    .Y(_112_)
  );
  BUF _649_ (
    .A(_004_),
    .Y(_114_)
  );
  BUF _650_ (
    .A(_004_),
    .Y(_116_)
  );
  BUF _651_ (
    .A(_004_),
    .Y(_118_)
  );
  BUF _652_ (
    .A(_004_),
    .Y(_120_)
  );
  BUF _653_ (
    .A(_004_),
    .Y(_121_)
  );
  BUF _654_ (
    .A(_004_),
    .Y(_123_)
  );
  BUF _655_ (
    .A(_004_),
    .Y(_125_)
  );
  BUF _656_ (
    .A(_004_),
    .Y(_127_)
  );
  BUF _657_ (
    .A(_004_),
    .Y(_129_)
  );
  DFFSR _658_ (
    .C(SD_CLK),
    .D(_002_),
    .Q(reception_complete),
    .R(_326_),
    .S(1'b0)
  );
  DFFSR _659_ (
    .C(SD_CLK),
    .D(_001_[0]),
    .Q(parallel_out[0]),
    .R(_327_),
    .S(1'b0)
  );
  DFFSR _660_ (
    .C(SD_CLK),
    .D(_001_[1]),
    .Q(parallel_out[1]),
    .R(_328_),
    .S(1'b0)
  );
  DFFSR _661_ (
    .C(SD_CLK),
    .D(_001_[2]),
    .Q(parallel_out[2]),
    .R(_329_),
    .S(1'b0)
  );
  DFFSR _662_ (
    .C(SD_CLK),
    .D(_001_[3]),
    .Q(parallel_out[3]),
    .R(_330_),
    .S(1'b0)
  );
  DFFSR _663_ (
    .C(SD_CLK),
    .D(_001_[4]),
    .Q(parallel_out[4]),
    .R(_331_),
    .S(1'b0)
  );
  DFFSR _664_ (
    .C(SD_CLK),
    .D(_001_[5]),
    .Q(parallel_out[5]),
    .R(_332_),
    .S(1'b0)
  );
  DFFSR _665_ (
    .C(SD_CLK),
    .D(_001_[6]),
    .Q(parallel_out[6]),
    .R(_333_),
    .S(1'b0)
  );
  DFFSR _666_ (
    .C(SD_CLK),
    .D(_001_[7]),
    .Q(parallel_out[7]),
    .R(_334_),
    .S(1'b0)
  );
  DFFSR _667_ (
    .C(SD_CLK),
    .D(_001_[8]),
    .Q(parallel_out[8]),
    .R(_335_),
    .S(1'b0)
  );
  DFFSR _668_ (
    .C(SD_CLK),
    .D(_001_[9]),
    .Q(parallel_out[9]),
    .R(_336_),
    .S(1'b0)
  );
  DFFSR _669_ (
    .C(SD_CLK),
    .D(_001_[10]),
    .Q(parallel_out[10]),
    .R(_337_),
    .S(1'b0)
  );
  DFFSR _670_ (
    .C(SD_CLK),
    .D(_001_[11]),
    .Q(parallel_out[11]),
    .R(_338_),
    .S(1'b0)
  );
  DFFSR _671_ (
    .C(SD_CLK),
    .D(_001_[12]),
    .Q(parallel_out[12]),
    .R(_339_),
    .S(1'b0)
  );
  DFFSR _672_ (
    .C(SD_CLK),
    .D(_001_[13]),
    .Q(parallel_out[13]),
    .R(_340_),
    .S(1'b0)
  );
  DFFSR _673_ (
    .C(SD_CLK),
    .D(_001_[14]),
    .Q(parallel_out[14]),
    .R(_341_),
    .S(1'b0)
  );
  DFFSR _674_ (
    .C(SD_CLK),
    .D(_001_[15]),
    .Q(parallel_out[15]),
    .R(_342_),
    .S(1'b0)
  );
  DFFSR _675_ (
    .C(SD_CLK),
    .D(_001_[16]),
    .Q(parallel_out[16]),
    .R(_343_),
    .S(1'b0)
  );
  DFFSR _676_ (
    .C(SD_CLK),
    .D(_001_[17]),
    .Q(parallel_out[17]),
    .R(_344_),
    .S(1'b0)
  );
  DFFSR _677_ (
    .C(SD_CLK),
    .D(_001_[18]),
    .Q(parallel_out[18]),
    .R(_345_),
    .S(1'b0)
  );
  DFFSR _678_ (
    .C(SD_CLK),
    .D(_001_[19]),
    .Q(parallel_out[19]),
    .R(_346_),
    .S(1'b0)
  );
  DFFSR _679_ (
    .C(SD_CLK),
    .D(_001_[20]),
    .Q(parallel_out[20]),
    .R(_347_),
    .S(1'b0)
  );
  DFFSR _680_ (
    .C(SD_CLK),
    .D(_001_[21]),
    .Q(parallel_out[21]),
    .R(_348_),
    .S(1'b0)
  );
  DFFSR _681_ (
    .C(SD_CLK),
    .D(_001_[22]),
    .Q(parallel_out[22]),
    .R(_349_),
    .S(1'b0)
  );
  DFFSR _682_ (
    .C(SD_CLK),
    .D(_001_[23]),
    .Q(parallel_out[23]),
    .R(_350_),
    .S(1'b0)
  );
  DFFSR _683_ (
    .C(SD_CLK),
    .D(_001_[24]),
    .Q(parallel_out[24]),
    .R(_351_),
    .S(1'b0)
  );
  DFFSR _684_ (
    .C(SD_CLK),
    .D(_001_[25]),
    .Q(parallel_out[25]),
    .R(_352_),
    .S(1'b0)
  );
  DFFSR _685_ (
    .C(SD_CLK),
    .D(_001_[26]),
    .Q(parallel_out[26]),
    .R(_353_),
    .S(1'b0)
  );
  DFFSR _686_ (
    .C(SD_CLK),
    .D(_001_[27]),
    .Q(parallel_out[27]),
    .R(_354_),
    .S(1'b0)
  );
  DFFSR _687_ (
    .C(SD_CLK),
    .D(_001_[28]),
    .Q(parallel_out[28]),
    .R(_355_),
    .S(1'b0)
  );
  DFFSR _688_ (
    .C(SD_CLK),
    .D(_001_[29]),
    .Q(parallel_out[29]),
    .R(_356_),
    .S(1'b0)
  );
  DFFSR _689_ (
    .C(SD_CLK),
    .D(_001_[30]),
    .Q(parallel_out[30]),
    .R(_357_),
    .S(1'b0)
  );
  DFFSR _690_ (
    .C(SD_CLK),
    .D(_001_[31]),
    .Q(parallel_out[31]),
    .R(_358_),
    .S(1'b0)
  );
  DFFSR _691_ (
    .C(SD_CLK),
    .D(_000_[0]),
    .Q(contador[0]),
    .R(_359_),
    .S(1'b0)
  );
  DFFSR _692_ (
    .C(SD_CLK),
    .D(_000_[1]),
    .Q(contador[1]),
    .R(_360_),
    .S(1'b0)
  );
  DFFSR _693_ (
    .C(SD_CLK),
    .D(_000_[2]),
    .Q(contador[2]),
    .R(_361_),
    .S(1'b0)
  );
  DFFSR _694_ (
    .C(SD_CLK),
    .D(_000_[3]),
    .Q(contador[3]),
    .R(_362_),
    .S(1'b0)
  );
  DFFSR _695_ (
    .C(SD_CLK),
    .D(_000_[4]),
    .Q(contador[4]),
    .R(_363_),
    .S(1'b0)
  );
  DFFSR _696_ (
    .C(SD_CLK),
    .D(_000_[5]),
    .Q(contador[5]),
    .R(_364_),
    .S(1'b0)
  );
  DFFSR _697_ (
    .C(SD_CLK),
    .D(_000_[6]),
    .Q(contador[6]),
    .R(_365_),
    .S(1'b0)
  );
  DFFSR _698_ (
    .C(SD_CLK),
    .D(_000_[7]),
    .Q(contador[7]),
    .R(_366_),
    .S(1'b0)
  );
  DFFSR _699_ (
    .C(SD_CLK),
    .D(_000_[8]),
    .Q(contador[8]),
    .R(_367_),
    .S(1'b0)
  );
  assign _003_ = RESET_L;
  assign _367_ = _004_;
  assign _139_ = contador[2];
  assign _226_ = contador[3];
  assign _291_ = contador[4];
  assign _307_ = contador[6];
  assign _314_ = contador[7];
  assign _055_ = contador[8];
  assign _111_ = reception_complete;
  assign _130_ = enable_stp;
  assign _002_ = _140_;
  assign _149_ = parallel_out[0];
  assign _158_ = parallel_out[1];
  assign _175_ = parallel_out[2];
  assign _192_ = parallel_out[3];
  assign _209_ = parallel_out[4];
  assign _227_ = parallel_out[5];
  assign _244_ = parallel_out[6];
  assign _262_ = parallel_out[7];
  assign _280_ = parallel_out[8];
  assign _285_ = parallel_out[9];
  assign _286_ = parallel_out[10];
  assign _287_ = parallel_out[11];
  assign _288_ = parallel_out[12];
  assign _289_ = parallel_out[13];
  assign _290_ = parallel_out[14];
  assign _292_ = parallel_out[15];
  assign _293_ = parallel_out[16];
  assign _294_ = parallel_out[17];
  assign _295_ = parallel_out[18];
  assign _296_ = parallel_out[19];
  assign _297_ = parallel_out[20];
  assign _298_ = parallel_out[21];
  assign _299_ = parallel_out[22];
  assign _300_ = parallel_out[23];
  assign _301_ = parallel_out[24];
  assign _302_ = parallel_out[25];
  assign _303_ = parallel_out[26];
  assign _304_ = parallel_out[27];
  assign _305_ = parallel_out[28];
  assign _306_ = parallel_out[29];
  assign _308_ = parallel_out[30];
  assign _309_ = parallel_out[31];
  assign _310_ = serial_in;
  assign _001_[0] = _311_;
  assign _001_[1] = _312_;
  assign _001_[2] = _313_;
  assign _001_[3] = _315_;
  assign _001_[4] = _316_;
  assign _001_[5] = _317_;
  assign _001_[6] = _318_;
  assign _001_[7] = _319_;
  assign _001_[8] = _320_;
  assign _001_[9] = _321_;
  assign _001_[10] = _322_;
  assign _001_[11] = _323_;
  assign _001_[12] = _324_;
  assign _001_[13] = _005_;
  assign _001_[14] = _006_;
  assign _001_[15] = _007_;
  assign _001_[16] = _008_;
  assign _001_[17] = _009_;
  assign _001_[18] = _010_;
  assign _001_[19] = _011_;
  assign _001_[20] = _012_;
  assign _001_[21] = _013_;
  assign _001_[22] = _014_;
  assign _001_[23] = _015_;
  assign _001_[24] = _016_;
  assign _001_[25] = _017_;
  assign _001_[26] = _018_;
  assign _001_[27] = _019_;
  assign _001_[28] = _020_;
  assign _001_[29] = _021_;
  assign _001_[30] = _022_;
  assign _001_[31] = _023_;
  assign _030_ = contador[0];
  assign _000_[0] = _032_;
  assign _034_ = contador[1];
  assign _000_[1] = _036_;
  assign _000_[2] = _038_;
  assign _000_[3] = _040_;
  assign _000_[4] = _042_;
  assign _044_ = contador[5];
  assign _000_[5] = _046_;
  assign _000_[6] = _048_;
  assign _000_[7] = _049_;
  assign _000_[8] = _051_;
  assign _326_ = _053_;
  assign _327_ = _056_;
  assign _328_ = _058_;
  assign _329_ = _060_;
  assign _330_ = _062_;
  assign _331_ = _064_;
  assign _332_ = _066_;
  assign _333_ = _068_;
  assign _334_ = _070_;
  assign _335_ = _072_;
  assign _336_ = _074_;
  assign _337_ = _075_;
  assign _338_ = _077_;
  assign _339_ = _079_;
  assign _340_ = _081_;
  assign _341_ = _083_;
  assign _342_ = _084_;
  assign _343_ = _086_;
  assign _344_ = _088_;
  assign _345_ = _090_;
  assign _346_ = _092_;
  assign _347_ = _093_;
  assign _348_ = _095_;
  assign _349_ = _097_;
  assign _350_ = _099_;
  assign _351_ = _101_;
  assign _352_ = _102_;
  assign _353_ = _104_;
  assign _354_ = _106_;
  assign _355_ = _108_;
  assign _356_ = _110_;
  assign _357_ = _112_;
  assign _358_ = _114_;
  assign _359_ = _116_;
  assign _360_ = _118_;
  assign _361_ = _120_;
  assign _362_ = _121_;
  assign _363_ = _123_;
  assign _364_ = _125_;
  assign _365_ = _127_;
  assign _366_ = _129_;
endmodule

module BloqueDATA(CLK, SD_CLK, RESET_L, timeout_Reg_Regs_DATA, writeRead_Regs_DATA, blockCount_Regs_DATA, multipleData_Regs_DATA, timeout_enable_Regs_DATA, FIFO_OK_FIFO_DATA, dataFromFIFO_FIFO_Phy, New_DAT_DMA_DATA, DATA_PIN_IN, writeFIFO_enable_Phy_FIFO, readFIFO_enable_Phy_FIFO, dataReadToFIFO_Phy_FIFO, transfer_complete_DATA_DMA, IO_enable_Phy_SD_CARD, DATA_PIN_OUT, pad_state_Phy_PAD, pad_enable_Phy_PAD);
  input CLK;
  input DATA_PIN_IN;
  output DATA_PIN_OUT;
  input FIFO_OK_FIFO_DATA;
  output IO_enable_Phy_SD_CARD;
  input New_DAT_DMA_DATA;
  input RESET_L;
  input SD_CLK;
  wire ack_IN_Phy_DATA;
  wire ack_OUT_DATA_Phy;
  input [3:0] blockCount_Regs_DATA;
  wire [3:0] blocks_DATA_Phy;
  wire complete_Phy_DATA;
  input [31:0] dataFromFIFO_FIFO_Phy;
  wire [31:0] dataParallel_Phy_PS;
  output [31:0] dataReadToFIFO_Phy_FIFO;
  wire [31:0] data_read_SP_Phy;
  wire enable_pts_Wrapper_Phy_PS;
  wire enable_stp_Wrapper_Phy_SP;
  wire idle_out_DATA_Phy;
  input multipleData_Regs_DATA;
  wire multiple_DATA_Phy;
  output pad_enable_Phy_PAD;
  output pad_state_Phy_PAD;
  output readFIFO_enable_Phy_FIFO;
  wire reception_complete_SP_Phy;
  wire reset_Wrapper_Phy_PS;
  wire serial_Ready_Phy_DATA;
  wire strobe_OUT_DATA_Phy;
  wire timeout_Phy_DATA;
  input [15:0] timeout_Reg_Regs_DATA;
  input timeout_enable_Regs_DATA;
  wire [15:0] timeout_value_DATA_Phy;
  output transfer_complete_DATA_DMA;
  wire transmission_complete_PS_Phy;
  output writeFIFO_enable_Phy_FIFO;
  wire writeReadPhysical_DATA_Phy;
  input writeRead_Regs_DATA;
  DATA_PHYSICAL CapaFisica (
    .IO_enable_Phy_SD_CARD(IO_enable_Phy_SD_CARD),
    .RESET_L(RESET_L),
    .SD_CLK(SD_CLK),
    .ack_IN_DATA_Phy(ack_OUT_DATA_Phy),
    .ack_OUT_Phy_DATA(ack_IN_Phy_DATA),
    .blocks_DATA_Phy(blocks_DATA_Phy),
    .complete_Phy_DATA(complete_Phy_DATA),
    .dataFromFIFO_FIFO_Phy(dataFromFIFO_FIFO_Phy),
    .dataParallel_Phy_PS(dataParallel_Phy_PS),
    .dataReadToFIFO_Phy_FIFO(dataReadToFIFO_Phy_FIFO),
    .data_read_SP_Phy(data_read_SP_Phy),
    .data_timeout_Phy_DATA(timeout_Phy_DATA),
    .enable_pts_Wrapper_Phy_PS(enable_pts_Wrapper_Phy_PS),
    .enable_stp_Wrapper_Phy_SP(enable_stp_Wrapper_Phy_SP),
    .idle_in_DATA_Phy(idle_out_DATA_Phy),
    .multiple_DATA_Phy(multiple_DATA_Phy),
    .pad_enable_Phy_PAD(pad_enable_Phy_PAD),
    .pad_state_Phy_PAD(pad_state_Phy_PAD),
    .readFIFO_enable_Phy_FIFO(readFIFO_enable_Phy_FIFO),
    .reception_complete_SP_Phy(reception_complete_SP_Phy),
    .reset_Wrapper_Phy_PS(reset_Wrapper_Phy_PS),
    .serial_Ready_Phy_DATA(serial_Ready_Phy_DATA),
    .strobe_IN_DATA_Phy(strobe_OUT_DATA_Phy),
    .timeout_Reg_DATA_Phy(timeout_value_DATA_Phy),
    .transmission_complete_PS_Phy(transmission_complete_PS_Phy),
    .writeFIFO_enable_Phy_FIFO(writeFIFO_enable_Phy_FIFO),
    .writeRead_DATA_Phy(writeReadPhysical_DATA_Phy)
  );
  DATA ControlDatos (
    .CLK(CLK),
    .RESET_L(RESET_L),
    .ack_IN_Phy_DATA(ack_IN_Phy_DATA),
    .ack_OUT_DATA_Phy(ack_OUT_DATA_Phy),
    .blockCount_Regs_DATA(blockCount_Regs_DATA),
    .blocks_DATA_Phy(blocks_DATA_Phy),
    .complete_Phy_DATA(complete_Phy_DATA),
    .fifo_OK_FIFO_DATA(FIFO_OK_FIFO_DATA),
    .idle_out_DATA_Phy(idle_out_DATA_Phy),
    .multipleData_Regs_DATA(multipleData_Regs_DATA),
    .multiple_DATA_Phy(multiple_DATA_Phy),
    .new_DAT_DMA_DATA(New_DAT_DMA_DATA),
    .serial_Ready_Phy_DATA(serial_Ready_Phy_DATA),
    .strobe_OUT_DATA_Phy(strobe_OUT_DATA_Phy),
    .timeout_Enable_Regs_DATA(timeout_enable_Regs_DATA),
    .timeout_Phy_DATA(timeout_Phy_DATA),
    .timeout_Reg_Regs_DATA(timeout_Reg_Regs_DATA),
    .timeout_value_DATA_Phy(timeout_value_DATA_Phy),
    .transfer_complete_DATA_DMA(transfer_complete_DATA_DMA),
    .writeReadPhysical_DATA_Phy(writeReadPhysical_DATA_Phy),
    .writeRead_Regs_DATA(writeRead_Regs_DATA)
  );
  PARALLEL_TO_SERIAL convert_paralelo_serial (
    .SD_CLK(SD_CLK),
    .enable_pts(enable_pts_Wrapper_Phy_PS),
    .parallel_complete(transmission_complete_PS_Phy),
    .reset_pts(reset_Wrapper_Phy_PS),
    .signal_in(dataParallel_Phy_PS),
    .signal_out(DATA_PIN_OUT)
  );
  \$paramod\SERIAL_TO_PARALLEL\SIZE=32  convert_serial_paralelo (
    .RESET_L(RESET_L),
    .SD_CLK(SD_CLK),
    .enable_stp(enable_stp_Wrapper_Phy_SP),
    .parallel_out(data_read_SP_Phy),
    .reception_complete(reception_complete_SP_Phy),
    .serial_in(DATA_PIN_IN)
  );
endmodule

module DATA(CLK, RESET_L, writeRead_Regs_DATA, blockCount_Regs_DATA, multipleData_Regs_DATA, timeout_Enable_Regs_DATA, timeout_Reg_Regs_DATA, new_DAT_DMA_DATA, serial_Ready_Phy_DATA, timeout_Phy_DATA, complete_Phy_DATA, ack_IN_Phy_DATA, fifo_OK_FIFO_DATA, transfer_complete_DATA_DMA, strobe_OUT_DATA_Phy, ack_OUT_DATA_Phy, blocks_DATA_Phy, timeout_value_DATA_Phy, writeReadPhysical_DATA_Phy, multiple_DATA_Phy, idle_out_DATA_Phy);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  input CLK;
  input RESET_L;
  wire STATE;
  input ack_IN_Phy_DATA;
  output ack_OUT_DATA_Phy;
  input [3:0] blockCount_Regs_DATA;
  output [3:0] blocks_DATA_Phy;
  input complete_Phy_DATA;
  input fifo_OK_FIFO_DATA;
  output idle_out_DATA_Phy;
  input multipleData_Regs_DATA;
  output multiple_DATA_Phy;
  input new_DAT_DMA_DATA;
  input serial_Ready_Phy_DATA;
  output strobe_OUT_DATA_Phy;
  input timeout_Enable_Regs_DATA;
  input timeout_Phy_DATA;
  input [15:0] timeout_Reg_Regs_DATA;
  output [15:0] timeout_value_DATA_Phy;
  output transfer_complete_DATA_DMA;
  output writeReadPhysical_DATA_Phy;
  input writeRead_Regs_DATA;
  NOT _07_ (
    .A(_02_),
    .Y(_03_)
  );
  NOT _08_ (
    .A(_04_),
    .Y(_06_)
  );
  DFF _09_ (
    .C(CLK),
    .D(_00_),
    .Q(STATE)
  );
  \$_DLATCH_P_  _10_ (
    .D(_01_),
    .E(STATE),
    .Q(timeout_value_DATA_Phy[7])
  );
  assign ack_OUT_DATA_Phy = timeout_value_DATA_Phy[7];
  assign blocks_DATA_Phy = { timeout_value_DATA_Phy[7], timeout_value_DATA_Phy[7], timeout_value_DATA_Phy[7], timeout_value_DATA_Phy[7] };
  assign multiple_DATA_Phy = timeout_value_DATA_Phy[7];
  assign strobe_OUT_DATA_Phy = timeout_value_DATA_Phy[7];
  assign { timeout_value_DATA_Phy[15:8], timeout_value_DATA_Phy[6:0] } = { timeout_value_DATA_Phy[7], timeout_value_DATA_Phy[7], timeout_value_DATA_Phy[7], timeout_value_DATA_Phy[7], timeout_value_DATA_Phy[7], timeout_value_DATA_Phy[7], timeout_value_DATA_Phy[7], timeout_value_DATA_Phy[7], timeout_value_DATA_Phy[7], timeout_value_DATA_Phy[7], timeout_value_DATA_Phy[7], timeout_value_DATA_Phy[7], timeout_value_DATA_Phy[7], timeout_value_DATA_Phy[7], timeout_value_DATA_Phy[7] };
  assign transfer_complete_DATA_DMA = timeout_value_DATA_Phy[7];
  assign writeReadPhysical_DATA_Phy = timeout_value_DATA_Phy[7];
  assign _05_ = 1'b0;
  assign _02_ = RESET_L;
  assign _00_ = _03_;
  assign _04_ = STATE;
  assign _01_ = _05_;
  assign idle_out_DATA_Phy = _06_;
endmodule

module DATA_PHYSICAL(SD_CLK, RESET_L, strobe_IN_DATA_Phy, ack_IN_DATA_Phy, timeout_Reg_DATA_Phy, blocks_DATA_Phy, writeRead_DATA_Phy, multiple_DATA_Phy, idle_in_DATA_Phy, transmission_complete_PS_Phy, reception_complete_SP_Phy, data_read_SP_Phy, dataFromFIFO_FIFO_Phy, serial_Ready_Phy_DATA, complete_Phy_DATA, ack_OUT_Phy_DATA, data_timeout_Phy_DATA, reset_Wrapper_Phy_PS, enable_pts_Wrapper_Phy_PS, enable_stp_Wrapper_Phy_SP, dataParallel_Phy_PS, pad_state_Phy_PAD, pad_enable_Phy_PAD, writeFIFO_enable_Phy_FIFO, readFIFO_enable_Phy_FIFO, dataReadToFIFO_Phy_FIFO, IO_enable_Phy_SD_CARD);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  output IO_enable_Phy_SD_CARD;
  input RESET_L;
  input SD_CLK;
  wire STATE;
  input ack_IN_DATA_Phy;
  output ack_OUT_Phy_DATA;
  input [3:0] blocks_DATA_Phy;
  output complete_Phy_DATA;
  input [31:0] dataFromFIFO_FIFO_Phy;
  output [31:0] dataParallel_Phy_PS;
  output [31:0] dataReadToFIFO_Phy_FIFO;
  input [31:0] data_read_SP_Phy;
  output data_timeout_Phy_DATA;
  output enable_pts_Wrapper_Phy_PS;
  output enable_stp_Wrapper_Phy_SP;
  input idle_in_DATA_Phy;
  input multiple_DATA_Phy;
  output pad_enable_Phy_PAD;
  output pad_state_Phy_PAD;
  output readFIFO_enable_Phy_FIFO;
  input reception_complete_SP_Phy;
  output reset_Wrapper_Phy_PS;
  output serial_Ready_Phy_DATA;
  input strobe_IN_DATA_Phy;
  input [15:0] timeout_Reg_DATA_Phy;
  input transmission_complete_PS_Phy;
  output writeFIFO_enable_Phy_FIFO;
  input writeRead_DATA_Phy;
  NOT _09_ (
    .A(_05_),
    .Y(_06_)
  );
  NOT _10_ (
    .A(_03_),
    .Y(_08_)
  );
  BUF _11_ (
    .A(_03_),
    .Y(_07_)
  );
  DFF _12_ (
    .C(SD_CLK),
    .D(_00_),
    .Q(STATE)
  );
  \$_DLATCH_P_  _13_ (
    .D(_02_),
    .E(STATE),
    .Q(reset_Wrapper_Phy_PS)
  );
  \$_DLATCH_P_  _14_ (
    .D(_01_),
    .E(STATE),
    .Q(dataParallel_Phy_PS[24])
  );
  assign IO_enable_Phy_SD_CARD = dataParallel_Phy_PS[24];
  assign ack_OUT_Phy_DATA = dataParallel_Phy_PS[24];
  assign complete_Phy_DATA = dataParallel_Phy_PS[24];
  assign { dataParallel_Phy_PS[31:25], dataParallel_Phy_PS[23:0] } = { dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24] };
  assign dataReadToFIFO_Phy_FIFO = { dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24], dataParallel_Phy_PS[24] };
  assign data_timeout_Phy_DATA = dataParallel_Phy_PS[24];
  assign enable_pts_Wrapper_Phy_PS = dataParallel_Phy_PS[24];
  assign enable_stp_Wrapper_Phy_SP = dataParallel_Phy_PS[24];
  assign pad_enable_Phy_PAD = dataParallel_Phy_PS[24];
  assign pad_state_Phy_PAD = dataParallel_Phy_PS[24];
  assign readFIFO_enable_Phy_FIFO = dataParallel_Phy_PS[24];
  assign writeFIFO_enable_Phy_FIFO = dataParallel_Phy_PS[24];
  assign _04_ = 1'b0;
  assign _03_ = STATE;
  assign _01_ = _04_;
  assign _05_ = RESET_L;
  assign _00_ = _06_;
  assign _02_ = _07_;
  assign serial_Ready_Phy_DATA = _08_;
endmodule

module PARALLEL_TO_SERIAL(enable_pts, reset_pts, SD_CLK, signal_in, signal_out, parallel_complete);
  wire [8:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire [31:0] _224_;
  wire [3:0] _225_;
  wire [1:0] _226_;
  wire _227_;
  wire [8:0] _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire [8:0] _232_;
  wire [8:0] _233_;
  wire _234_;
  wire [31:0] _235_;
  wire [31:0] _236_;
  wire [95:0] _237_;
  wire [95:0] _238_;
  wire [95:0] _239_;
  wire [95:0] _240_;
  wire [95:0] _241_;
  wire [95:0] _242_;
  wire [31:0] _243_;
  wire [31:0] _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire [31:0] _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  input SD_CLK;
  wire [8:0] contador;
  input enable_pts;
  output parallel_complete;
  input reset_pts;
  input [31:0] signal_in;
  output signal_out;
  NOT _261_ (
    .A(_122_),
    .Y(_164_)
  );
  NOT _262_ (
    .A(_080_),
    .Y(_166_)
  );
  NOR _263_ (
    .A(_091_),
    .B(_166_),
    .Y(_168_)
  );
  NOT _264_ (
    .A(_091_),
    .Y(_171_)
  );
  NOR _265_ (
    .A(_156_),
    .B(_155_),
    .Y(_172_)
  );
  NOT _266_ (
    .A(_172_),
    .Y(_174_)
  );
  NOR _267_ (
    .A(_174_),
    .B(_006_),
    .Y(_175_)
  );
  NOT _268_ (
    .A(_184_),
    .Y(_177_)
  );
  NOR _269_ (
    .A(_047_),
    .B(_154_),
    .Y(_178_)
  );
  NAND _270_ (
    .A(_178_),
    .B(_177_),
    .Y(_179_)
  );
  NOT _271_ (
    .A(_005_),
    .Y(_180_)
  );
  NOT _272_ (
    .A(_157_),
    .Y(_181_)
  );
  NOR _273_ (
    .A(_181_),
    .B(_169_),
    .Y(_183_)
  );
  NAND _274_ (
    .A(_183_),
    .B(_180_),
    .Y(_185_)
  );
  NOR _275_ (
    .A(_185_),
    .B(_179_),
    .Y(_186_)
  );
  NAND _276_ (
    .A(_186_),
    .B(_175_),
    .Y(_187_)
  );
  NOR _277_ (
    .A(_187_),
    .B(_171_),
    .Y(_189_)
  );
  NOR _278_ (
    .A(_189_),
    .B(_168_),
    .Y(_190_)
  );
  NOR _279_ (
    .A(_190_),
    .B(_164_),
    .Y(_133_)
  );
  NOR _280_ (
    .A(_189_),
    .B(_164_),
    .Y(_192_)
  );
  NOT _281_ (
    .A(_192_),
    .Y(_194_)
  );
  NOT _282_ (
    .A(_155_),
    .Y(_195_)
  );
  NAND _283_ (
    .A(_195_),
    .B(_171_),
    .Y(_197_)
  );
  NAND _284_ (
    .A(_155_),
    .B(_091_),
    .Y(_198_)
  );
  NAND _285_ (
    .A(_198_),
    .B(_197_),
    .Y(_200_)
  );
  NOR _286_ (
    .A(_200_),
    .B(_194_),
    .Y(_158_)
  );
  NOT _287_ (
    .A(_156_),
    .Y(_202_)
  );
  NOR _288_ (
    .A(_198_),
    .B(_202_),
    .Y(_203_)
  );
  NAND _289_ (
    .A(_198_),
    .B(_202_),
    .Y(_205_)
  );
  NAND _290_ (
    .A(_205_),
    .B(_122_),
    .Y(_206_)
  );
  NOR _291_ (
    .A(_206_),
    .B(_203_),
    .Y(_159_)
  );
  NAND _292_ (
    .A(_203_),
    .B(_005_),
    .Y(_208_)
  );
  NOT _293_ (
    .A(_208_),
    .Y(_210_)
  );
  NOT _294_ (
    .A(_203_),
    .Y(_211_)
  );
  NAND _295_ (
    .A(_211_),
    .B(_180_),
    .Y(_213_)
  );
  NAND _296_ (
    .A(_213_),
    .B(_122_),
    .Y(_214_)
  );
  NOR _297_ (
    .A(_214_),
    .B(_210_),
    .Y(_160_)
  );
  NOT _298_ (
    .A(_006_),
    .Y(_216_)
  );
  NOR _299_ (
    .A(_208_),
    .B(_216_),
    .Y(_218_)
  );
  NAND _300_ (
    .A(_208_),
    .B(_216_),
    .Y(_219_)
  );
  NAND _301_ (
    .A(_219_),
    .B(_122_),
    .Y(_221_)
  );
  NOR _302_ (
    .A(_221_),
    .B(_218_),
    .Y(_161_)
  );
  NAND _303_ (
    .A(_218_),
    .B(_154_),
    .Y(_223_)
  );
  NOT _304_ (
    .A(_223_),
    .Y(_007_)
  );
  NOT _305_ (
    .A(_154_),
    .Y(_009_)
  );
  NOT _306_ (
    .A(_218_),
    .Y(_010_)
  );
  NAND _307_ (
    .A(_010_),
    .B(_009_),
    .Y(_012_)
  );
  NAND _308_ (
    .A(_012_),
    .B(_122_),
    .Y(_013_)
  );
  NOR _309_ (
    .A(_013_),
    .B(_007_),
    .Y(_162_)
  );
  NOR _310_ (
    .A(_007_),
    .B(_157_),
    .Y(_015_)
  );
  NOR _311_ (
    .A(_223_),
    .B(_181_),
    .Y(_017_)
  );
  NOT _312_ (
    .A(_017_),
    .Y(_018_)
  );
  NAND _313_ (
    .A(_018_),
    .B(_192_),
    .Y(_020_)
  );
  NOR _314_ (
    .A(_020_),
    .B(_015_),
    .Y(_163_)
  );
  NOR _315_ (
    .A(_017_),
    .B(_169_),
    .Y(_022_)
  );
  NAND _316_ (
    .A(_017_),
    .B(_169_),
    .Y(_023_)
  );
  NAND _317_ (
    .A(_023_),
    .B(_122_),
    .Y(_025_)
  );
  NOR _318_ (
    .A(_025_),
    .B(_022_),
    .Y(_165_)
  );
  NOR _319_ (
    .A(_023_),
    .B(_177_),
    .Y(_027_)
  );
  NAND _320_ (
    .A(_023_),
    .B(_177_),
    .Y(_028_)
  );
  NAND _321_ (
    .A(_028_),
    .B(_122_),
    .Y(_030_)
  );
  NOR _322_ (
    .A(_030_),
    .B(_027_),
    .Y(_167_)
  );
  NOT _323_ (
    .A(_047_),
    .Y(_032_)
  );
  NOR _324_ (
    .A(_027_),
    .B(_032_),
    .Y(_033_)
  );
  NOT _325_ (
    .A(_027_),
    .Y(_035_)
  );
  NOR _326_ (
    .A(_035_),
    .B(_047_),
    .Y(_036_)
  );
  NOR _327_ (
    .A(_036_),
    .B(_033_),
    .Y(_038_)
  );
  NOR _328_ (
    .A(_038_),
    .B(_164_),
    .Y(_170_)
  );
  NOT _329_ (
    .A(_176_),
    .Y(_040_)
  );
  NOR _330_ (
    .A(_187_),
    .B(_040_),
    .Y(_041_)
  );
  NOR _331_ (
    .A(_182_),
    .B(_009_),
    .Y(_043_)
  );
  NOR _332_ (
    .A(_011_),
    .B(_154_),
    .Y(_044_)
  );
  NOR _333_ (
    .A(_044_),
    .B(_043_),
    .Y(_046_)
  );
  NOR _334_ (
    .A(_046_),
    .B(_216_),
    .Y(_048_)
  );
  NOR _335_ (
    .A(_031_),
    .B(_154_),
    .Y(_050_)
  );
  NOR _336_ (
    .A(_207_),
    .B(_009_),
    .Y(_051_)
  );
  NOR _337_ (
    .A(_051_),
    .B(_050_),
    .Y(_053_)
  );
  NOR _338_ (
    .A(_053_),
    .B(_006_),
    .Y(_054_)
  );
  NOR _339_ (
    .A(_054_),
    .B(_048_),
    .Y(_055_)
  );
  NOR _340_ (
    .A(_055_),
    .B(_202_),
    .Y(_056_)
  );
  NAND _341_ (
    .A(_037_),
    .B(_009_),
    .Y(_057_)
  );
  NAND _342_ (
    .A(_212_),
    .B(_154_),
    .Y(_058_)
  );
  NAND _343_ (
    .A(_058_),
    .B(_057_),
    .Y(_059_)
  );
  NOR _344_ (
    .A(_059_),
    .B(_006_),
    .Y(_060_)
  );
  NOT _345_ (
    .A(_191_),
    .Y(_061_)
  );
  NOR _346_ (
    .A(_061_),
    .B(_009_),
    .Y(_062_)
  );
  NAND _347_ (
    .A(_016_),
    .B(_009_),
    .Y(_063_)
  );
  NAND _348_ (
    .A(_063_),
    .B(_006_),
    .Y(_064_)
  );
  NOR _349_ (
    .A(_064_),
    .B(_062_),
    .Y(_065_)
  );
  NOR _350_ (
    .A(_065_),
    .B(_060_),
    .Y(_066_)
  );
  NOR _351_ (
    .A(_066_),
    .B(_156_),
    .Y(_067_)
  );
  NOR _352_ (
    .A(_067_),
    .B(_056_),
    .Y(_068_)
  );
  NOR _353_ (
    .A(_068_),
    .B(_180_),
    .Y(_069_)
  );
  NOR _354_ (
    .A(_196_),
    .B(_009_),
    .Y(_070_)
  );
  NOR _355_ (
    .A(_021_),
    .B(_154_),
    .Y(_071_)
  );
  NOR _356_ (
    .A(_071_),
    .B(_070_),
    .Y(_072_)
  );
  NOR _357_ (
    .A(_072_),
    .B(_216_),
    .Y(_073_)
  );
  NOR _358_ (
    .A(_042_),
    .B(_154_),
    .Y(_074_)
  );
  NOR _359_ (
    .A(_217_),
    .B(_009_),
    .Y(_075_)
  );
  NOR _360_ (
    .A(_075_),
    .B(_074_),
    .Y(_076_)
  );
  NOR _361_ (
    .A(_076_),
    .B(_006_),
    .Y(_077_)
  );
  NOR _362_ (
    .A(_077_),
    .B(_073_),
    .Y(_078_)
  );
  NOR _363_ (
    .A(_078_),
    .B(_202_),
    .Y(_079_)
  );
  NAND _364_ (
    .A(_049_),
    .B(_009_),
    .Y(_081_)
  );
  NAND _365_ (
    .A(_222_),
    .B(_154_),
    .Y(_082_)
  );
  NAND _366_ (
    .A(_082_),
    .B(_081_),
    .Y(_083_)
  );
  NOR _367_ (
    .A(_083_),
    .B(_006_),
    .Y(_084_)
  );
  NOT _368_ (
    .A(_201_),
    .Y(_085_)
  );
  NOR _369_ (
    .A(_085_),
    .B(_009_),
    .Y(_086_)
  );
  NAND _370_ (
    .A(_026_),
    .B(_009_),
    .Y(_087_)
  );
  NAND _371_ (
    .A(_087_),
    .B(_006_),
    .Y(_088_)
  );
  NOR _372_ (
    .A(_088_),
    .B(_086_),
    .Y(_089_)
  );
  NOR _373_ (
    .A(_089_),
    .B(_084_),
    .Y(_090_)
  );
  NOR _374_ (
    .A(_090_),
    .B(_156_),
    .Y(_092_)
  );
  NOR _375_ (
    .A(_092_),
    .B(_079_),
    .Y(_093_)
  );
  NOR _376_ (
    .A(_093_),
    .B(_005_),
    .Y(_094_)
  );
  NOR _377_ (
    .A(_094_),
    .B(_069_),
    .Y(_095_)
  );
  NOR _378_ (
    .A(_095_),
    .B(_195_),
    .Y(_096_)
  );
  NAND _379_ (
    .A(_034_),
    .B(_009_),
    .Y(_097_)
  );
  NOT _380_ (
    .A(_209_),
    .Y(_098_)
  );
  NOR _381_ (
    .A(_098_),
    .B(_009_),
    .Y(_099_)
  );
  NOR _382_ (
    .A(_099_),
    .B(_006_),
    .Y(_100_)
  );
  NAND _383_ (
    .A(_100_),
    .B(_097_),
    .Y(_101_)
  );
  NAND _384_ (
    .A(_188_),
    .B(_154_),
    .Y(_102_)
  );
  NOT _385_ (
    .A(_014_),
    .Y(_103_)
  );
  NOR _386_ (
    .A(_103_),
    .B(_154_),
    .Y(_104_)
  );
  NOR _387_ (
    .A(_104_),
    .B(_216_),
    .Y(_105_)
  );
  NAND _388_ (
    .A(_105_),
    .B(_102_),
    .Y(_106_)
  );
  NAND _389_ (
    .A(_106_),
    .B(_101_),
    .Y(_107_)
  );
  NOR _390_ (
    .A(_107_),
    .B(_180_),
    .Y(_108_)
  );
  NAND _391_ (
    .A(_045_),
    .B(_009_),
    .Y(_109_)
  );
  NAND _392_ (
    .A(_220_),
    .B(_154_),
    .Y(_110_)
  );
  NAND _393_ (
    .A(_110_),
    .B(_109_),
    .Y(_111_)
  );
  NOR _394_ (
    .A(_111_),
    .B(_006_),
    .Y(_112_)
  );
  NOT _395_ (
    .A(_199_),
    .Y(_113_)
  );
  NOR _396_ (
    .A(_113_),
    .B(_009_),
    .Y(_114_)
  );
  NAND _397_ (
    .A(_024_),
    .B(_009_),
    .Y(_115_)
  );
  NAND _398_ (
    .A(_115_),
    .B(_006_),
    .Y(_116_)
  );
  NOR _399_ (
    .A(_116_),
    .B(_114_),
    .Y(_117_)
  );
  NOR _400_ (
    .A(_117_),
    .B(_112_),
    .Y(_118_)
  );
  NAND _401_ (
    .A(_118_),
    .B(_180_),
    .Y(_119_)
  );
  NAND _402_ (
    .A(_119_),
    .B(_156_),
    .Y(_120_)
  );
  NOR _403_ (
    .A(_120_),
    .B(_108_),
    .Y(_121_)
  );
  NAND _404_ (
    .A(_121_),
    .B(_195_),
    .Y(_123_)
  );
  NOR _405_ (
    .A(_193_),
    .B(_009_),
    .Y(_124_)
  );
  NOR _406_ (
    .A(_019_),
    .B(_154_),
    .Y(_125_)
  );
  NOR _407_ (
    .A(_125_),
    .B(_124_),
    .Y(_126_)
  );
  NOR _408_ (
    .A(_126_),
    .B(_216_),
    .Y(_127_)
  );
  NOR _409_ (
    .A(_039_),
    .B(_154_),
    .Y(_128_)
  );
  NOR _410_ (
    .A(_215_),
    .B(_009_),
    .Y(_129_)
  );
  NOR _411_ (
    .A(_129_),
    .B(_128_),
    .Y(_130_)
  );
  NOR _412_ (
    .A(_130_),
    .B(_006_),
    .Y(_131_)
  );
  NOR _413_ (
    .A(_131_),
    .B(_127_),
    .Y(_132_)
  );
  NOR _414_ (
    .A(_132_),
    .B(_180_),
    .Y(_134_)
  );
  NOR _415_ (
    .A(_204_),
    .B(_009_),
    .Y(_135_)
  );
  NOR _416_ (
    .A(_029_),
    .B(_154_),
    .Y(_136_)
  );
  NOR _417_ (
    .A(_136_),
    .B(_135_),
    .Y(_137_)
  );
  NOR _418_ (
    .A(_137_),
    .B(_216_),
    .Y(_138_)
  );
  NOR _419_ (
    .A(_052_),
    .B(_154_),
    .Y(_139_)
  );
  NOR _420_ (
    .A(_008_),
    .B(_009_),
    .Y(_140_)
  );
  NOR _421_ (
    .A(_140_),
    .B(_139_),
    .Y(_141_)
  );
  NOR _422_ (
    .A(_141_),
    .B(_006_),
    .Y(_142_)
  );
  NOR _423_ (
    .A(_142_),
    .B(_138_),
    .Y(_143_)
  );
  NOR _424_ (
    .A(_143_),
    .B(_005_),
    .Y(_144_)
  );
  NOR _425_ (
    .A(_144_),
    .B(_134_),
    .Y(_145_)
  );
  NOR _426_ (
    .A(_145_),
    .B(_174_),
    .Y(_146_)
  );
  NOT _427_ (
    .A(_169_),
    .Y(_147_)
  );
  NAND _428_ (
    .A(_181_),
    .B(_147_),
    .Y(_148_)
  );
  NOR _429_ (
    .A(_148_),
    .B(_146_),
    .Y(_149_)
  );
  NAND _430_ (
    .A(_149_),
    .B(_123_),
    .Y(_150_)
  );
  NOR _431_ (
    .A(_150_),
    .B(_096_),
    .Y(_151_)
  );
  NOR _432_ (
    .A(_151_),
    .B(_041_),
    .Y(_152_)
  );
  NAND _433_ (
    .A(_122_),
    .B(_091_),
    .Y(_153_)
  );
  NOR _434_ (
    .A(_153_),
    .B(_152_),
    .Y(_173_)
  );
  DFF _435_ (
    .C(SD_CLK),
    .D(_002_),
    .Q(signal_out)
  );
  DFF _436_ (
    .C(SD_CLK),
    .D(_001_),
    .Q(parallel_complete)
  );
  DFF _437_ (
    .C(SD_CLK),
    .D(_000_[0]),
    .Q(contador[0])
  );
  DFF _438_ (
    .C(SD_CLK),
    .D(_000_[1]),
    .Q(contador[1])
  );
  DFF _439_ (
    .C(SD_CLK),
    .D(_000_[2]),
    .Q(contador[2])
  );
  DFF _440_ (
    .C(SD_CLK),
    .D(_000_[3]),
    .Q(contador[3])
  );
  DFF _441_ (
    .C(SD_CLK),
    .D(_000_[4]),
    .Q(contador[4])
  );
  DFF _442_ (
    .C(SD_CLK),
    .D(_000_[5]),
    .Q(contador[5])
  );
  DFF _443_ (
    .C(SD_CLK),
    .D(_000_[6]),
    .Q(contador[6])
  );
  DFF _444_ (
    .C(SD_CLK),
    .D(_000_[7]),
    .Q(contador[7])
  );
  DFF _445_ (
    .C(SD_CLK),
    .D(_000_[8]),
    .Q(contador[8])
  );
  assign _005_ = contador[2];
  assign _006_ = contador[3];
  assign _154_ = contador[4];
  assign _169_ = contador[6];
  assign _184_ = contador[7];
  assign _047_ = contador[8];
  assign _080_ = parallel_complete;
  assign _091_ = enable_pts;
  assign _122_ = reset_pts;
  assign _001_ = _133_;
  assign _155_ = contador[0];
  assign _156_ = contador[1];
  assign _157_ = contador[5];
  assign _000_[0] = _158_;
  assign _000_[1] = _159_;
  assign _000_[2] = _160_;
  assign _000_[3] = _161_;
  assign _000_[4] = _162_;
  assign _000_[5] = _163_;
  assign _000_[6] = _165_;
  assign _000_[7] = _167_;
  assign _000_[8] = _170_;
  assign _002_ = _173_;
  assign _176_ = signal_out;
  assign _182_ = signal_in[0];
  assign _188_ = signal_in[1];
  assign _191_ = signal_in[2];
  assign _193_ = signal_in[3];
  assign _196_ = signal_in[4];
  assign _199_ = signal_in[5];
  assign _201_ = signal_in[6];
  assign _204_ = signal_in[7];
  assign _207_ = signal_in[8];
  assign _209_ = signal_in[9];
  assign _212_ = signal_in[10];
  assign _215_ = signal_in[11];
  assign _217_ = signal_in[12];
  assign _220_ = signal_in[13];
  assign _222_ = signal_in[14];
  assign _008_ = signal_in[15];
  assign _011_ = signal_in[16];
  assign _014_ = signal_in[17];
  assign _016_ = signal_in[18];
  assign _019_ = signal_in[19];
  assign _021_ = signal_in[20];
  assign _024_ = signal_in[21];
  assign _026_ = signal_in[22];
  assign _029_ = signal_in[23];
  assign _031_ = signal_in[24];
  assign _034_ = signal_in[25];
  assign _037_ = signal_in[26];
  assign _039_ = signal_in[27];
  assign _042_ = signal_in[28];
  assign _045_ = signal_in[29];
  assign _049_ = signal_in[30];
  assign _052_ = signal_in[31];
endmodule

module SERIAL_TO_PARALLEL(serial_in, enable_stp, SD_CLK, RESET_L, reception_complete, parallel_out);
  wire [8:0] _000_;
  wire [31:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire [31:0] _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire [3:0] _368_;
  wire [1:0] _369_;
  wire _370_;
  wire [8:0] _371_;
  wire _372_;
  wire _373_;
  wire [31:0] _374_;
  wire [8:0] _375_;
  wire [31:0] _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  input RESET_L;
  input SD_CLK;
  wire [8:0] contador;
  input enable_stp;
  output [31:0] parallel_out;
  output reception_complete;
  input serial_in;
  NOT _381_ (
    .A(_003_),
    .Y(_004_)
  );
  NOT _382_ (
    .A(_130_),
    .Y(_024_)
  );
  NAND _383_ (
    .A(_024_),
    .B(_111_),
    .Y(_025_)
  );
  NOR _384_ (
    .A(_055_),
    .B(_314_),
    .Y(_026_)
  );
  NAND _385_ (
    .A(_026_),
    .B(_044_),
    .Y(_027_)
  );
  NOR _386_ (
    .A(_034_),
    .B(_030_),
    .Y(_028_)
  );
  NOT _387_ (
    .A(_139_),
    .Y(_029_)
  );
  NOT _388_ (
    .A(_226_),
    .Y(_031_)
  );
  NAND _389_ (
    .A(_031_),
    .B(_029_),
    .Y(_033_)
  );
  NOT _390_ (
    .A(_291_),
    .Y(_035_)
  );
  NOT _391_ (
    .A(_307_),
    .Y(_037_)
  );
  NAND _392_ (
    .A(_037_),
    .B(_035_),
    .Y(_039_)
  );
  NOR _393_ (
    .A(_039_),
    .B(_033_),
    .Y(_041_)
  );
  NAND _394_ (
    .A(_041_),
    .B(_028_),
    .Y(_043_)
  );
  NOR _395_ (
    .A(_043_),
    .B(_027_),
    .Y(_045_)
  );
  NAND _396_ (
    .A(_045_),
    .B(_130_),
    .Y(_047_)
  );
  NAND _397_ (
    .A(_047_),
    .B(_025_),
    .Y(_140_)
  );
  NOT _398_ (
    .A(_158_),
    .Y(_050_)
  );
  NOR _399_ (
    .A(_045_),
    .B(_050_),
    .Y(_052_)
  );
  NOT _400_ (
    .A(_149_),
    .Y(_054_)
  );
  NOT _401_ (
    .A(_027_),
    .Y(_057_)
  );
  NOT _402_ (
    .A(_028_),
    .Y(_059_)
  );
  NOR _403_ (
    .A(_226_),
    .B(_139_),
    .Y(_061_)
  );
  NOR _404_ (
    .A(_307_),
    .B(_291_),
    .Y(_063_)
  );
  NAND _405_ (
    .A(_063_),
    .B(_061_),
    .Y(_065_)
  );
  NOR _406_ (
    .A(_065_),
    .B(_059_),
    .Y(_067_)
  );
  NAND _407_ (
    .A(_067_),
    .B(_057_),
    .Y(_069_)
  );
  NOR _408_ (
    .A(_069_),
    .B(_054_),
    .Y(_071_)
  );
  NOR _409_ (
    .A(_071_),
    .B(_052_),
    .Y(_073_)
  );
  NOR _410_ (
    .A(_073_),
    .B(_024_),
    .Y(_311_)
  );
  NOT _411_ (
    .A(_175_),
    .Y(_076_)
  );
  NOR _412_ (
    .A(_045_),
    .B(_076_),
    .Y(_078_)
  );
  NOR _413_ (
    .A(_069_),
    .B(_050_),
    .Y(_080_)
  );
  NOR _414_ (
    .A(_080_),
    .B(_078_),
    .Y(_082_)
  );
  NOR _415_ (
    .A(_082_),
    .B(_024_),
    .Y(_312_)
  );
  NOT _416_ (
    .A(_192_),
    .Y(_085_)
  );
  NOR _417_ (
    .A(_045_),
    .B(_085_),
    .Y(_087_)
  );
  NOR _418_ (
    .A(_069_),
    .B(_076_),
    .Y(_089_)
  );
  NOR _419_ (
    .A(_089_),
    .B(_087_),
    .Y(_091_)
  );
  NOR _420_ (
    .A(_091_),
    .B(_024_),
    .Y(_313_)
  );
  NOT _421_ (
    .A(_209_),
    .Y(_094_)
  );
  NOR _422_ (
    .A(_045_),
    .B(_094_),
    .Y(_096_)
  );
  NOR _423_ (
    .A(_069_),
    .B(_085_),
    .Y(_098_)
  );
  NOR _424_ (
    .A(_098_),
    .B(_096_),
    .Y(_100_)
  );
  NOR _425_ (
    .A(_100_),
    .B(_024_),
    .Y(_315_)
  );
  NOT _426_ (
    .A(_227_),
    .Y(_103_)
  );
  NOR _427_ (
    .A(_045_),
    .B(_103_),
    .Y(_105_)
  );
  NOR _428_ (
    .A(_069_),
    .B(_094_),
    .Y(_107_)
  );
  NOR _429_ (
    .A(_107_),
    .B(_105_),
    .Y(_109_)
  );
  NOR _430_ (
    .A(_109_),
    .B(_024_),
    .Y(_316_)
  );
  NOT _431_ (
    .A(_244_),
    .Y(_113_)
  );
  NOR _432_ (
    .A(_045_),
    .B(_113_),
    .Y(_115_)
  );
  NOR _433_ (
    .A(_069_),
    .B(_103_),
    .Y(_117_)
  );
  NOR _434_ (
    .A(_117_),
    .B(_115_),
    .Y(_119_)
  );
  NOR _435_ (
    .A(_119_),
    .B(_024_),
    .Y(_317_)
  );
  NOT _436_ (
    .A(_262_),
    .Y(_122_)
  );
  NOR _437_ (
    .A(_045_),
    .B(_122_),
    .Y(_124_)
  );
  NOR _438_ (
    .A(_069_),
    .B(_113_),
    .Y(_126_)
  );
  NOR _439_ (
    .A(_126_),
    .B(_124_),
    .Y(_128_)
  );
  NOR _440_ (
    .A(_128_),
    .B(_024_),
    .Y(_318_)
  );
  NOT _441_ (
    .A(_280_),
    .Y(_131_)
  );
  NOR _442_ (
    .A(_045_),
    .B(_131_),
    .Y(_132_)
  );
  NOR _443_ (
    .A(_069_),
    .B(_122_),
    .Y(_133_)
  );
  NOR _444_ (
    .A(_133_),
    .B(_132_),
    .Y(_134_)
  );
  NOR _445_ (
    .A(_134_),
    .B(_024_),
    .Y(_319_)
  );
  NOT _446_ (
    .A(_285_),
    .Y(_135_)
  );
  NOR _447_ (
    .A(_045_),
    .B(_135_),
    .Y(_136_)
  );
  NOR _448_ (
    .A(_069_),
    .B(_131_),
    .Y(_137_)
  );
  NOR _449_ (
    .A(_137_),
    .B(_136_),
    .Y(_138_)
  );
  NOR _450_ (
    .A(_138_),
    .B(_024_),
    .Y(_320_)
  );
  NOT _451_ (
    .A(_286_),
    .Y(_141_)
  );
  NOR _452_ (
    .A(_045_),
    .B(_141_),
    .Y(_142_)
  );
  NOR _453_ (
    .A(_069_),
    .B(_135_),
    .Y(_143_)
  );
  NOR _454_ (
    .A(_143_),
    .B(_142_),
    .Y(_144_)
  );
  NOR _455_ (
    .A(_144_),
    .B(_024_),
    .Y(_321_)
  );
  NOT _456_ (
    .A(_287_),
    .Y(_145_)
  );
  NOR _457_ (
    .A(_045_),
    .B(_145_),
    .Y(_146_)
  );
  NOR _458_ (
    .A(_069_),
    .B(_141_),
    .Y(_147_)
  );
  NOR _459_ (
    .A(_147_),
    .B(_146_),
    .Y(_148_)
  );
  NOR _460_ (
    .A(_148_),
    .B(_024_),
    .Y(_322_)
  );
  NOT _461_ (
    .A(_288_),
    .Y(_150_)
  );
  NOR _462_ (
    .A(_045_),
    .B(_150_),
    .Y(_151_)
  );
  NOR _463_ (
    .A(_069_),
    .B(_145_),
    .Y(_152_)
  );
  NOR _464_ (
    .A(_152_),
    .B(_151_),
    .Y(_153_)
  );
  NOR _465_ (
    .A(_153_),
    .B(_024_),
    .Y(_323_)
  );
  NOT _466_ (
    .A(_289_),
    .Y(_154_)
  );
  NOR _467_ (
    .A(_045_),
    .B(_154_),
    .Y(_155_)
  );
  NOR _468_ (
    .A(_069_),
    .B(_150_),
    .Y(_156_)
  );
  NOR _469_ (
    .A(_156_),
    .B(_155_),
    .Y(_157_)
  );
  NOR _470_ (
    .A(_157_),
    .B(_024_),
    .Y(_324_)
  );
  NOT _471_ (
    .A(_290_),
    .Y(_159_)
  );
  NOR _472_ (
    .A(_045_),
    .B(_159_),
    .Y(_160_)
  );
  NOR _473_ (
    .A(_069_),
    .B(_154_),
    .Y(_161_)
  );
  NOR _474_ (
    .A(_161_),
    .B(_160_),
    .Y(_162_)
  );
  NOR _475_ (
    .A(_162_),
    .B(_024_),
    .Y(_005_)
  );
  NOT _476_ (
    .A(_292_),
    .Y(_163_)
  );
  NOR _477_ (
    .A(_045_),
    .B(_163_),
    .Y(_164_)
  );
  NOR _478_ (
    .A(_069_),
    .B(_159_),
    .Y(_165_)
  );
  NOR _479_ (
    .A(_165_),
    .B(_164_),
    .Y(_166_)
  );
  NOR _480_ (
    .A(_166_),
    .B(_024_),
    .Y(_006_)
  );
  NOT _481_ (
    .A(_293_),
    .Y(_167_)
  );
  NOR _482_ (
    .A(_045_),
    .B(_167_),
    .Y(_168_)
  );
  NOR _483_ (
    .A(_069_),
    .B(_163_),
    .Y(_169_)
  );
  NOR _484_ (
    .A(_169_),
    .B(_168_),
    .Y(_170_)
  );
  NOR _485_ (
    .A(_170_),
    .B(_024_),
    .Y(_007_)
  );
  NOT _486_ (
    .A(_294_),
    .Y(_171_)
  );
  NOR _487_ (
    .A(_045_),
    .B(_171_),
    .Y(_172_)
  );
  NOR _488_ (
    .A(_069_),
    .B(_167_),
    .Y(_173_)
  );
  NOR _489_ (
    .A(_173_),
    .B(_172_),
    .Y(_174_)
  );
  NOR _490_ (
    .A(_174_),
    .B(_024_),
    .Y(_008_)
  );
  NOT _491_ (
    .A(_295_),
    .Y(_176_)
  );
  NOR _492_ (
    .A(_045_),
    .B(_176_),
    .Y(_177_)
  );
  NOR _493_ (
    .A(_069_),
    .B(_171_),
    .Y(_178_)
  );
  NOR _494_ (
    .A(_178_),
    .B(_177_),
    .Y(_179_)
  );
  NOR _495_ (
    .A(_179_),
    .B(_024_),
    .Y(_009_)
  );
  NOT _496_ (
    .A(_296_),
    .Y(_180_)
  );
  NOR _497_ (
    .A(_045_),
    .B(_180_),
    .Y(_181_)
  );
  NOR _498_ (
    .A(_069_),
    .B(_176_),
    .Y(_182_)
  );
  NOR _499_ (
    .A(_182_),
    .B(_181_),
    .Y(_183_)
  );
  NOR _500_ (
    .A(_183_),
    .B(_024_),
    .Y(_010_)
  );
  NOT _501_ (
    .A(_297_),
    .Y(_184_)
  );
  NOR _502_ (
    .A(_045_),
    .B(_184_),
    .Y(_185_)
  );
  NOR _503_ (
    .A(_069_),
    .B(_180_),
    .Y(_186_)
  );
  NOR _504_ (
    .A(_186_),
    .B(_185_),
    .Y(_187_)
  );
  NOR _505_ (
    .A(_187_),
    .B(_024_),
    .Y(_011_)
  );
  NOT _506_ (
    .A(_298_),
    .Y(_188_)
  );
  NOR _507_ (
    .A(_045_),
    .B(_188_),
    .Y(_189_)
  );
  NOR _508_ (
    .A(_069_),
    .B(_184_),
    .Y(_190_)
  );
  NOR _509_ (
    .A(_190_),
    .B(_189_),
    .Y(_191_)
  );
  NOR _510_ (
    .A(_191_),
    .B(_024_),
    .Y(_012_)
  );
  NOT _511_ (
    .A(_299_),
    .Y(_193_)
  );
  NOR _512_ (
    .A(_045_),
    .B(_193_),
    .Y(_194_)
  );
  NOR _513_ (
    .A(_069_),
    .B(_188_),
    .Y(_195_)
  );
  NOR _514_ (
    .A(_195_),
    .B(_194_),
    .Y(_196_)
  );
  NOR _515_ (
    .A(_196_),
    .B(_024_),
    .Y(_013_)
  );
  NOT _516_ (
    .A(_300_),
    .Y(_197_)
  );
  NOR _517_ (
    .A(_045_),
    .B(_197_),
    .Y(_198_)
  );
  NOR _518_ (
    .A(_069_),
    .B(_193_),
    .Y(_199_)
  );
  NOR _519_ (
    .A(_199_),
    .B(_198_),
    .Y(_200_)
  );
  NOR _520_ (
    .A(_200_),
    .B(_024_),
    .Y(_014_)
  );
  NOT _521_ (
    .A(_301_),
    .Y(_201_)
  );
  NOR _522_ (
    .A(_045_),
    .B(_201_),
    .Y(_202_)
  );
  NOR _523_ (
    .A(_069_),
    .B(_197_),
    .Y(_203_)
  );
  NOR _524_ (
    .A(_203_),
    .B(_202_),
    .Y(_204_)
  );
  NOR _525_ (
    .A(_204_),
    .B(_024_),
    .Y(_015_)
  );
  NOT _526_ (
    .A(_302_),
    .Y(_205_)
  );
  NOR _527_ (
    .A(_045_),
    .B(_205_),
    .Y(_206_)
  );
  NOR _528_ (
    .A(_069_),
    .B(_201_),
    .Y(_207_)
  );
  NOR _529_ (
    .A(_207_),
    .B(_206_),
    .Y(_208_)
  );
  NOR _530_ (
    .A(_208_),
    .B(_024_),
    .Y(_016_)
  );
  NOT _531_ (
    .A(_303_),
    .Y(_210_)
  );
  NOR _532_ (
    .A(_045_),
    .B(_210_),
    .Y(_211_)
  );
  NOR _533_ (
    .A(_069_),
    .B(_205_),
    .Y(_212_)
  );
  NOR _534_ (
    .A(_212_),
    .B(_211_),
    .Y(_213_)
  );
  NOR _535_ (
    .A(_213_),
    .B(_024_),
    .Y(_017_)
  );
  NOT _536_ (
    .A(_304_),
    .Y(_214_)
  );
  NOR _537_ (
    .A(_045_),
    .B(_214_),
    .Y(_215_)
  );
  NOR _538_ (
    .A(_069_),
    .B(_210_),
    .Y(_216_)
  );
  NOR _539_ (
    .A(_216_),
    .B(_215_),
    .Y(_217_)
  );
  NOR _540_ (
    .A(_217_),
    .B(_024_),
    .Y(_018_)
  );
  NOT _541_ (
    .A(_305_),
    .Y(_218_)
  );
  NOR _542_ (
    .A(_045_),
    .B(_218_),
    .Y(_219_)
  );
  NOR _543_ (
    .A(_069_),
    .B(_214_),
    .Y(_220_)
  );
  NOR _544_ (
    .A(_220_),
    .B(_219_),
    .Y(_221_)
  );
  NOR _545_ (
    .A(_221_),
    .B(_024_),
    .Y(_019_)
  );
  NOT _546_ (
    .A(_306_),
    .Y(_222_)
  );
  NOR _547_ (
    .A(_045_),
    .B(_222_),
    .Y(_223_)
  );
  NOR _548_ (
    .A(_069_),
    .B(_218_),
    .Y(_224_)
  );
  NOR _549_ (
    .A(_224_),
    .B(_223_),
    .Y(_225_)
  );
  NOR _550_ (
    .A(_225_),
    .B(_024_),
    .Y(_020_)
  );
  NOT _551_ (
    .A(_308_),
    .Y(_228_)
  );
  NOR _552_ (
    .A(_045_),
    .B(_228_),
    .Y(_229_)
  );
  NOR _553_ (
    .A(_069_),
    .B(_222_),
    .Y(_230_)
  );
  NOR _554_ (
    .A(_230_),
    .B(_229_),
    .Y(_231_)
  );
  NOR _555_ (
    .A(_231_),
    .B(_024_),
    .Y(_021_)
  );
  NOT _556_ (
    .A(_309_),
    .Y(_232_)
  );
  NOR _557_ (
    .A(_045_),
    .B(_232_),
    .Y(_233_)
  );
  NOR _558_ (
    .A(_069_),
    .B(_228_),
    .Y(_234_)
  );
  NOR _559_ (
    .A(_234_),
    .B(_233_),
    .Y(_235_)
  );
  NOR _560_ (
    .A(_235_),
    .B(_024_),
    .Y(_022_)
  );
  NOT _561_ (
    .A(_310_),
    .Y(_236_)
  );
  NOR _562_ (
    .A(_045_),
    .B(_236_),
    .Y(_237_)
  );
  NOR _563_ (
    .A(_069_),
    .B(_232_),
    .Y(_238_)
  );
  NOR _564_ (
    .A(_238_),
    .B(_237_),
    .Y(_239_)
  );
  NOR _565_ (
    .A(_239_),
    .B(_024_),
    .Y(_023_)
  );
  NAND _566_ (
    .A(_030_),
    .B(_024_),
    .Y(_240_)
  );
  NOR _567_ (
    .A(_045_),
    .B(_030_),
    .Y(_241_)
  );
  NAND _568_ (
    .A(_241_),
    .B(_130_),
    .Y(_242_)
  );
  NAND _569_ (
    .A(_242_),
    .B(_240_),
    .Y(_032_)
  );
  NOT _570_ (
    .A(_030_),
    .Y(_243_)
  );
  NOT _571_ (
    .A(_034_),
    .Y(_245_)
  );
  NOR _572_ (
    .A(_245_),
    .B(_243_),
    .Y(_246_)
  );
  NOR _573_ (
    .A(_246_),
    .B(_028_),
    .Y(_247_)
  );
  NOR _574_ (
    .A(_247_),
    .B(_024_),
    .Y(_248_)
  );
  NOR _575_ (
    .A(_034_),
    .B(_130_),
    .Y(_249_)
  );
  NOR _576_ (
    .A(_249_),
    .B(_248_),
    .Y(_036_)
  );
  NAND _577_ (
    .A(_246_),
    .B(_130_),
    .Y(_250_)
  );
  NOR _578_ (
    .A(_250_),
    .B(_029_),
    .Y(_251_)
  );
  NAND _579_ (
    .A(_034_),
    .B(_030_),
    .Y(_252_)
  );
  NOR _580_ (
    .A(_252_),
    .B(_024_),
    .Y(_253_)
  );
  NOR _581_ (
    .A(_253_),
    .B(_139_),
    .Y(_254_)
  );
  NOR _582_ (
    .A(_254_),
    .B(_251_),
    .Y(_038_)
  );
  NOR _583_ (
    .A(_251_),
    .B(_226_),
    .Y(_255_)
  );
  NAND _584_ (
    .A(_226_),
    .B(_139_),
    .Y(_256_)
  );
  NOR _585_ (
    .A(_256_),
    .B(_250_),
    .Y(_257_)
  );
  NOR _586_ (
    .A(_257_),
    .B(_255_),
    .Y(_040_)
  );
  NOR _587_ (
    .A(_257_),
    .B(_291_),
    .Y(_258_)
  );
  NOT _588_ (
    .A(_256_),
    .Y(_259_)
  );
  NAND _589_ (
    .A(_259_),
    .B(_253_),
    .Y(_260_)
  );
  NOR _590_ (
    .A(_260_),
    .B(_035_),
    .Y(_261_)
  );
  NOR _591_ (
    .A(_261_),
    .B(_258_),
    .Y(_042_)
  );
  NOR _592_ (
    .A(_261_),
    .B(_044_),
    .Y(_263_)
  );
  NAND _593_ (
    .A(_261_),
    .B(_044_),
    .Y(_264_)
  );
  NAND _594_ (
    .A(_264_),
    .B(_047_),
    .Y(_265_)
  );
  NOR _595_ (
    .A(_265_),
    .B(_263_),
    .Y(_046_)
  );
  NAND _596_ (
    .A(_264_),
    .B(_307_),
    .Y(_266_)
  );
  NOT _597_ (
    .A(_044_),
    .Y(_267_)
  );
  NAND _598_ (
    .A(_257_),
    .B(_291_),
    .Y(_268_)
  );
  NOR _599_ (
    .A(_268_),
    .B(_267_),
    .Y(_269_)
  );
  NAND _600_ (
    .A(_269_),
    .B(_037_),
    .Y(_270_)
  );
  NAND _601_ (
    .A(_270_),
    .B(_266_),
    .Y(_048_)
  );
  NOT _602_ (
    .A(_314_),
    .Y(_271_)
  );
  NOR _603_ (
    .A(_256_),
    .B(_252_),
    .Y(_272_)
  );
  NAND _604_ (
    .A(_307_),
    .B(_291_),
    .Y(_273_)
  );
  NAND _605_ (
    .A(_044_),
    .B(_130_),
    .Y(_274_)
  );
  NOR _606_ (
    .A(_274_),
    .B(_273_),
    .Y(_275_)
  );
  NAND _607_ (
    .A(_275_),
    .B(_272_),
    .Y(_276_)
  );
  NOR _608_ (
    .A(_276_),
    .B(_271_),
    .Y(_277_)
  );
  NOT _609_ (
    .A(_276_),
    .Y(_278_)
  );
  NOR _610_ (
    .A(_278_),
    .B(_314_),
    .Y(_279_)
  );
  NOR _611_ (
    .A(_279_),
    .B(_277_),
    .Y(_049_)
  );
  NOR _612_ (
    .A(_277_),
    .B(_055_),
    .Y(_281_)
  );
  NOT _613_ (
    .A(_055_),
    .Y(_282_)
  );
  NOT _614_ (
    .A(_277_),
    .Y(_283_)
  );
  NOR _615_ (
    .A(_283_),
    .B(_282_),
    .Y(_284_)
  );
  NOR _616_ (
    .A(_284_),
    .B(_281_),
    .Y(_051_)
  );
  BUF _617_ (
    .A(_004_),
    .Y(_053_)
  );
  BUF _618_ (
    .A(_004_),
    .Y(_056_)
  );
  BUF _619_ (
    .A(_004_),
    .Y(_058_)
  );
  BUF _620_ (
    .A(_004_),
    .Y(_060_)
  );
  BUF _621_ (
    .A(_004_),
    .Y(_062_)
  );
  BUF _622_ (
    .A(_004_),
    .Y(_064_)
  );
  BUF _623_ (
    .A(_004_),
    .Y(_066_)
  );
  BUF _624_ (
    .A(_004_),
    .Y(_068_)
  );
  BUF _625_ (
    .A(_004_),
    .Y(_070_)
  );
  BUF _626_ (
    .A(_004_),
    .Y(_072_)
  );
  BUF _627_ (
    .A(_004_),
    .Y(_074_)
  );
  BUF _628_ (
    .A(_004_),
    .Y(_075_)
  );
  BUF _629_ (
    .A(_004_),
    .Y(_077_)
  );
  BUF _630_ (
    .A(_004_),
    .Y(_079_)
  );
  BUF _631_ (
    .A(_004_),
    .Y(_081_)
  );
  BUF _632_ (
    .A(_004_),
    .Y(_083_)
  );
  BUF _633_ (
    .A(_004_),
    .Y(_084_)
  );
  BUF _634_ (
    .A(_004_),
    .Y(_086_)
  );
  BUF _635_ (
    .A(_004_),
    .Y(_088_)
  );
  BUF _636_ (
    .A(_004_),
    .Y(_090_)
  );
  BUF _637_ (
    .A(_004_),
    .Y(_092_)
  );
  BUF _638_ (
    .A(_004_),
    .Y(_093_)
  );
  BUF _639_ (
    .A(_004_),
    .Y(_095_)
  );
  BUF _640_ (
    .A(_004_),
    .Y(_097_)
  );
  BUF _641_ (
    .A(_004_),
    .Y(_099_)
  );
  BUF _642_ (
    .A(_004_),
    .Y(_101_)
  );
  BUF _643_ (
    .A(_004_),
    .Y(_102_)
  );
  BUF _644_ (
    .A(_004_),
    .Y(_104_)
  );
  BUF _645_ (
    .A(_004_),
    .Y(_106_)
  );
  BUF _646_ (
    .A(_004_),
    .Y(_108_)
  );
  BUF _647_ (
    .A(_004_),
    .Y(_110_)
  );
  BUF _648_ (
    .A(_004_),
    .Y(_112_)
  );
  BUF _649_ (
    .A(_004_),
    .Y(_114_)
  );
  BUF _650_ (
    .A(_004_),
    .Y(_116_)
  );
  BUF _651_ (
    .A(_004_),
    .Y(_118_)
  );
  BUF _652_ (
    .A(_004_),
    .Y(_120_)
  );
  BUF _653_ (
    .A(_004_),
    .Y(_121_)
  );
  BUF _654_ (
    .A(_004_),
    .Y(_123_)
  );
  BUF _655_ (
    .A(_004_),
    .Y(_125_)
  );
  BUF _656_ (
    .A(_004_),
    .Y(_127_)
  );
  BUF _657_ (
    .A(_004_),
    .Y(_129_)
  );
  DFFSR _658_ (
    .C(SD_CLK),
    .D(_002_),
    .Q(reception_complete),
    .R(_326_),
    .S(1'b0)
  );
  DFFSR _659_ (
    .C(SD_CLK),
    .D(_001_[0]),
    .Q(parallel_out[0]),
    .R(_327_),
    .S(1'b0)
  );
  DFFSR _660_ (
    .C(SD_CLK),
    .D(_001_[1]),
    .Q(parallel_out[1]),
    .R(_328_),
    .S(1'b0)
  );
  DFFSR _661_ (
    .C(SD_CLK),
    .D(_001_[2]),
    .Q(parallel_out[2]),
    .R(_329_),
    .S(1'b0)
  );
  DFFSR _662_ (
    .C(SD_CLK),
    .D(_001_[3]),
    .Q(parallel_out[3]),
    .R(_330_),
    .S(1'b0)
  );
  DFFSR _663_ (
    .C(SD_CLK),
    .D(_001_[4]),
    .Q(parallel_out[4]),
    .R(_331_),
    .S(1'b0)
  );
  DFFSR _664_ (
    .C(SD_CLK),
    .D(_001_[5]),
    .Q(parallel_out[5]),
    .R(_332_),
    .S(1'b0)
  );
  DFFSR _665_ (
    .C(SD_CLK),
    .D(_001_[6]),
    .Q(parallel_out[6]),
    .R(_333_),
    .S(1'b0)
  );
  DFFSR _666_ (
    .C(SD_CLK),
    .D(_001_[7]),
    .Q(parallel_out[7]),
    .R(_334_),
    .S(1'b0)
  );
  DFFSR _667_ (
    .C(SD_CLK),
    .D(_001_[8]),
    .Q(parallel_out[8]),
    .R(_335_),
    .S(1'b0)
  );
  DFFSR _668_ (
    .C(SD_CLK),
    .D(_001_[9]),
    .Q(parallel_out[9]),
    .R(_336_),
    .S(1'b0)
  );
  DFFSR _669_ (
    .C(SD_CLK),
    .D(_001_[10]),
    .Q(parallel_out[10]),
    .R(_337_),
    .S(1'b0)
  );
  DFFSR _670_ (
    .C(SD_CLK),
    .D(_001_[11]),
    .Q(parallel_out[11]),
    .R(_338_),
    .S(1'b0)
  );
  DFFSR _671_ (
    .C(SD_CLK),
    .D(_001_[12]),
    .Q(parallel_out[12]),
    .R(_339_),
    .S(1'b0)
  );
  DFFSR _672_ (
    .C(SD_CLK),
    .D(_001_[13]),
    .Q(parallel_out[13]),
    .R(_340_),
    .S(1'b0)
  );
  DFFSR _673_ (
    .C(SD_CLK),
    .D(_001_[14]),
    .Q(parallel_out[14]),
    .R(_341_),
    .S(1'b0)
  );
  DFFSR _674_ (
    .C(SD_CLK),
    .D(_001_[15]),
    .Q(parallel_out[15]),
    .R(_342_),
    .S(1'b0)
  );
  DFFSR _675_ (
    .C(SD_CLK),
    .D(_001_[16]),
    .Q(parallel_out[16]),
    .R(_343_),
    .S(1'b0)
  );
  DFFSR _676_ (
    .C(SD_CLK),
    .D(_001_[17]),
    .Q(parallel_out[17]),
    .R(_344_),
    .S(1'b0)
  );
  DFFSR _677_ (
    .C(SD_CLK),
    .D(_001_[18]),
    .Q(parallel_out[18]),
    .R(_345_),
    .S(1'b0)
  );
  DFFSR _678_ (
    .C(SD_CLK),
    .D(_001_[19]),
    .Q(parallel_out[19]),
    .R(_346_),
    .S(1'b0)
  );
  DFFSR _679_ (
    .C(SD_CLK),
    .D(_001_[20]),
    .Q(parallel_out[20]),
    .R(_347_),
    .S(1'b0)
  );
  DFFSR _680_ (
    .C(SD_CLK),
    .D(_001_[21]),
    .Q(parallel_out[21]),
    .R(_348_),
    .S(1'b0)
  );
  DFFSR _681_ (
    .C(SD_CLK),
    .D(_001_[22]),
    .Q(parallel_out[22]),
    .R(_349_),
    .S(1'b0)
  );
  DFFSR _682_ (
    .C(SD_CLK),
    .D(_001_[23]),
    .Q(parallel_out[23]),
    .R(_350_),
    .S(1'b0)
  );
  DFFSR _683_ (
    .C(SD_CLK),
    .D(_001_[24]),
    .Q(parallel_out[24]),
    .R(_351_),
    .S(1'b0)
  );
  DFFSR _684_ (
    .C(SD_CLK),
    .D(_001_[25]),
    .Q(parallel_out[25]),
    .R(_352_),
    .S(1'b0)
  );
  DFFSR _685_ (
    .C(SD_CLK),
    .D(_001_[26]),
    .Q(parallel_out[26]),
    .R(_353_),
    .S(1'b0)
  );
  DFFSR _686_ (
    .C(SD_CLK),
    .D(_001_[27]),
    .Q(parallel_out[27]),
    .R(_354_),
    .S(1'b0)
  );
  DFFSR _687_ (
    .C(SD_CLK),
    .D(_001_[28]),
    .Q(parallel_out[28]),
    .R(_355_),
    .S(1'b0)
  );
  DFFSR _688_ (
    .C(SD_CLK),
    .D(_001_[29]),
    .Q(parallel_out[29]),
    .R(_356_),
    .S(1'b0)
  );
  DFFSR _689_ (
    .C(SD_CLK),
    .D(_001_[30]),
    .Q(parallel_out[30]),
    .R(_357_),
    .S(1'b0)
  );
  DFFSR _690_ (
    .C(SD_CLK),
    .D(_001_[31]),
    .Q(parallel_out[31]),
    .R(_358_),
    .S(1'b0)
  );
  DFFSR _691_ (
    .C(SD_CLK),
    .D(_000_[0]),
    .Q(contador[0]),
    .R(_359_),
    .S(1'b0)
  );
  DFFSR _692_ (
    .C(SD_CLK),
    .D(_000_[1]),
    .Q(contador[1]),
    .R(_360_),
    .S(1'b0)
  );
  DFFSR _693_ (
    .C(SD_CLK),
    .D(_000_[2]),
    .Q(contador[2]),
    .R(_361_),
    .S(1'b0)
  );
  DFFSR _694_ (
    .C(SD_CLK),
    .D(_000_[3]),
    .Q(contador[3]),
    .R(_362_),
    .S(1'b0)
  );
  DFFSR _695_ (
    .C(SD_CLK),
    .D(_000_[4]),
    .Q(contador[4]),
    .R(_363_),
    .S(1'b0)
  );
  DFFSR _696_ (
    .C(SD_CLK),
    .D(_000_[5]),
    .Q(contador[5]),
    .R(_364_),
    .S(1'b0)
  );
  DFFSR _697_ (
    .C(SD_CLK),
    .D(_000_[6]),
    .Q(contador[6]),
    .R(_365_),
    .S(1'b0)
  );
  DFFSR _698_ (
    .C(SD_CLK),
    .D(_000_[7]),
    .Q(contador[7]),
    .R(_366_),
    .S(1'b0)
  );
  DFFSR _699_ (
    .C(SD_CLK),
    .D(_000_[8]),
    .Q(contador[8]),
    .R(_367_),
    .S(1'b0)
  );
  assign _003_ = RESET_L;
  assign _367_ = _004_;
  assign _139_ = contador[2];
  assign _226_ = contador[3];
  assign _291_ = contador[4];
  assign _307_ = contador[6];
  assign _314_ = contador[7];
  assign _055_ = contador[8];
  assign _111_ = reception_complete;
  assign _130_ = enable_stp;
  assign _002_ = _140_;
  assign _149_ = parallel_out[0];
  assign _158_ = parallel_out[1];
  assign _175_ = parallel_out[2];
  assign _192_ = parallel_out[3];
  assign _209_ = parallel_out[4];
  assign _227_ = parallel_out[5];
  assign _244_ = parallel_out[6];
  assign _262_ = parallel_out[7];
  assign _280_ = parallel_out[8];
  assign _285_ = parallel_out[9];
  assign _286_ = parallel_out[10];
  assign _287_ = parallel_out[11];
  assign _288_ = parallel_out[12];
  assign _289_ = parallel_out[13];
  assign _290_ = parallel_out[14];
  assign _292_ = parallel_out[15];
  assign _293_ = parallel_out[16];
  assign _294_ = parallel_out[17];
  assign _295_ = parallel_out[18];
  assign _296_ = parallel_out[19];
  assign _297_ = parallel_out[20];
  assign _298_ = parallel_out[21];
  assign _299_ = parallel_out[22];
  assign _300_ = parallel_out[23];
  assign _301_ = parallel_out[24];
  assign _302_ = parallel_out[25];
  assign _303_ = parallel_out[26];
  assign _304_ = parallel_out[27];
  assign _305_ = parallel_out[28];
  assign _306_ = parallel_out[29];
  assign _308_ = parallel_out[30];
  assign _309_ = parallel_out[31];
  assign _310_ = serial_in;
  assign _001_[0] = _311_;
  assign _001_[1] = _312_;
  assign _001_[2] = _313_;
  assign _001_[3] = _315_;
  assign _001_[4] = _316_;
  assign _001_[5] = _317_;
  assign _001_[6] = _318_;
  assign _001_[7] = _319_;
  assign _001_[8] = _320_;
  assign _001_[9] = _321_;
  assign _001_[10] = _322_;
  assign _001_[11] = _323_;
  assign _001_[12] = _324_;
  assign _001_[13] = _005_;
  assign _001_[14] = _006_;
  assign _001_[15] = _007_;
  assign _001_[16] = _008_;
  assign _001_[17] = _009_;
  assign _001_[18] = _010_;
  assign _001_[19] = _011_;
  assign _001_[20] = _012_;
  assign _001_[21] = _013_;
  assign _001_[22] = _014_;
  assign _001_[23] = _015_;
  assign _001_[24] = _016_;
  assign _001_[25] = _017_;
  assign _001_[26] = _018_;
  assign _001_[27] = _019_;
  assign _001_[28] = _020_;
  assign _001_[29] = _021_;
  assign _001_[30] = _022_;
  assign _001_[31] = _023_;
  assign _030_ = contador[0];
  assign _000_[0] = _032_;
  assign _034_ = contador[1];
  assign _000_[1] = _036_;
  assign _000_[2] = _038_;
  assign _000_[3] = _040_;
  assign _000_[4] = _042_;
  assign _044_ = contador[5];
  assign _000_[5] = _046_;
  assign _000_[6] = _048_;
  assign _000_[7] = _049_;
  assign _000_[8] = _051_;
  assign _326_ = _053_;
  assign _327_ = _056_;
  assign _328_ = _058_;
  assign _329_ = _060_;
  assign _330_ = _062_;
  assign _331_ = _064_;
  assign _332_ = _066_;
  assign _333_ = _068_;
  assign _334_ = _070_;
  assign _335_ = _072_;
  assign _336_ = _074_;
  assign _337_ = _075_;
  assign _338_ = _077_;
  assign _339_ = _079_;
  assign _340_ = _081_;
  assign _341_ = _083_;
  assign _342_ = _084_;
  assign _343_ = _086_;
  assign _344_ = _088_;
  assign _345_ = _090_;
  assign _346_ = _092_;
  assign _347_ = _093_;
  assign _348_ = _095_;
  assign _349_ = _097_;
  assign _350_ = _099_;
  assign _351_ = _101_;
  assign _352_ = _102_;
  assign _353_ = _104_;
  assign _354_ = _106_;
  assign _355_ = _108_;
  assign _356_ = _110_;
  assign _357_ = _112_;
  assign _358_ = _114_;
  assign _359_ = _116_;
  assign _360_ = _118_;
  assign _361_ = _120_;
  assign _362_ = _121_;
  assign _363_ = _123_;
  assign _364_ = _125_;
  assign _365_ = _127_;
  assign _366_ = _129_;
endmodule
